### ISSUE TITLE
Powershell error during determine capabilities with activated Device-Guard

### ISSUE THREAD

**Issue by Stefan75** [Microsoft/vsts-agent#1259] opened 2017-10-23 10:39 UTC
Hello,

I try to use the windows version of the agent on our test-machines.
These test-machines are installed with an active Device-Guard (e.g. Application White-Listing AWL, App-Blocker).
I have signed the agent and also the included powershell scripts with our corporate key so that execution is allowed.
(e.g. bin\powershell\Add-PowerShellCapabilities.ps1)
But there is an error during evaluation of the agent capabilities.
(It seems that the used technique of including other ps1 files with the ‘.’ operator is not allowed)

## Have you try trouble shooting doc?
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting
Nothing found

## Agent version and platform
2.123.0

OS of the machine running the agent? OSX/Windows/Linux...
Windows

## VSTS type and version
VisualStudio.com

## What's not working?
It seems that the agent is not able to determine the capabilities of the machine because the powershell based implementation does not support an activated Device-Guard.
(because of the used '.' operator which seems to be a security topic)

## Agent and Worker's diag log
```
[2017-10-16 16:07:10Z INFO ProcessInvoker] Starting process:
[2017-10-16 16:07:10Z INFO ProcessInvoker]   File name: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
[2017-10-16 16:07:10Z INFO ProcessInvoker]   Arguments: '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\vstsagent\A1\bin\powershell\Add-Capabilities.ps1'"'
[2017-10-16 16:07:10Z INFO ProcessInvoker]   Working directory: 'C:\vstsagent\A1\bin\powershell'
[2017-10-16 16:07:10Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2017-10-16 16:07:10Z INFO ProcessInvoker]   Encoding web name:  ; code page: ''
[2017-10-16 16:07:10Z INFO ProcessInvoker]   Force kill process on cancellation: 'True'
[2017-10-16 16:07:10Z INFO ProcessInvoker] Process started with process id 20772, waiting for process exit.
[2017-10-16 16:07:10Z INFO PowerShellCapabilitiesProvider] STDERR: C:\vstsagent\A1\bin\powershell\Add-Capabilities.ps1 : Cannot dot-source this command because it was defined in a 
[2017-10-16 16:07:10Z INFO PowerShellCapabilitiesProvider] STDERR: different language mode. To invoke this command without importing its contents, omit the '.' operator.
[2017-10-16 16:07:10Z INFO PowerShellCapabilitiesProvider] STDERR: At line:1 char:1
[2017-10-16 16:07:10Z INFO PowerShellCapabilitiesProvider] STDERR: + . 'C:\vstsagent\A1\bin\powershell\Add-Capabilities.ps1'
[2017-10-16 16:07:10Z INFO PowerShellCapabilitiesProvider] STDERR: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2017-10-16 16:07:10Z INFO PowerShellCapabilitiesProvider] STDERR:     + CategoryInfo          : InvalidOperation: (:) [Add-Capabilities.ps1], NotSupportedException
[2017-10-16 16:07:10Z INFO PowerShellCapabilitiesProvider] STDERR:     + FullyQualifiedErrorId : DotSourceNotSupported,Add-Capabilities.ps1
[2017-10-16 16:07:10Z INFO PowerShellCapabilitiesProvider] STDERR:  
[2017-10-16 16:07:10Z INFO ProcessInvoker] Finished process with exit code 1, and elapsed time 00:00:00.2707353.
```

I am not a powershell expert - but I guess the reason is that in Add-Capabilities.ps1 other ps1 files are dynamically  "inlined" / executed.

From Add-Capabilities.ps1:
```powershell
[CmdletBinding()]
param()

Import-Module -Name 'Microsoft.PowerShell.Management'
Import-Module -Name 'Microsoft.PowerShell.Utility'
$ErrorActionPreference = 'Stop'
Import-Module -Name $PSScriptRoot\CapabilityHelpers

# Run each capability script.
foreach ($item in (Get-ChildItem -LiteralPath "$PSScriptRoot" -Filter "Add-*Capabilities.ps1")) {
    if ($item.Name -eq ([System.IO.Path]::GetFileName($PSCommandPath))) {
        continue;
    }

    Write-Host "& $($item.FullName)"
    try {
        & $item.FullName
    } catch {
        Write-Host ($_ | Out-String)
    }
}
```

See also following links:
https://www.sysadmins.lv/blog-en/powershell-50-and-applocker-when-security-doesnt-mean-security.aspx
https://www.sysadmins.lv/blog-en/powershell-50-and-applocker-when-security-doesnt-mean-security-part-2.aspx
https://stackoverflow.com/questions/36092541/powershell-cannot-dot-source-this-command-because-it-was-defined-in-a-different/36092806

**Comment by stephenmichaelf** [comment] 2017-10-30 13:10
@Stefan75 could you try replacing Add-Capabilities.ps1 with the attached file and let me know if it works? (Unzip and write over Add-Capabilities.ps1 in the powershell folder.

[Add-Capabilities.zip](https://github.com/Microsoft/vsts-agent/files/1427282/Add-Capabilities.zip)

**Comment by Stefan75** [comment] 2017-11-21 18:01
Hello,

thanks for the answer.

It took me some time to get my fingers on a simulation system. 
I checked the changed Add-Capabilities.ps1 version, but sadly it does not help.

It seems for me that the problem is the Import-Module or the the "&" operator -  I am not quite sure.
Maybe I have some time to perform some additional research at the system.

**Comment by TingluoHuang** [comment] 2018-06-26 19:34
I think this is an environment issue rather than agent issue.
the problem is in your environment, powershell is in Constrained Language Mode.

I find a doc talks about bypass the Constrained Mode in powershell, you might want to give a shut.
1. install PowerShell 2 on the machine.
2. in the Add-Capbilities.ps1, add `PowerShell -version 2` before running any statements.

https://pentestn00b.wordpress.com/2017/03/20/simple-bypass-for-powershell-constrained-language-mode/

I am going to close this issue for now, please reopen if you need more help.

**Closed by TingluoHuang** 2018-06-26 19:34 UTC
