### ISSUE TITLE
CurlException when publishing artifacts (only reported by customer in Belgium using telenet)

### ISSUE THREAD

**Issue by NielsWillems** [Microsoft/vsts-agent#938] opened 2017-04-25 09:31 UTC
## **Agent version and platform**
Version of your agent?  2.115.0 which runs as a service. 
<br>
OS of the machine running the agent? OSX Sierra
<br>
## **VSTS type and version**
VSTS online
<br>
## **What's not working?** 
Copy Publish Artifact build step throws exceptions when uploading. Recently updated to this version and it worked in the beginning but after a while it failed on this step every time. Get Sources is also extremely slow since updating. I've checked the connection and speeds which seem to be fine (DL: 230Mbit, UL: 25Mbit). Tried updating openssl but no luck.

> An error occurred while sending the request.'.
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Failure when receiving data from the peer    at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)    at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)    --- End of inner exception stack trace ---    at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d3.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Net.Http.HttpClient.<FinishSendAsync>d58.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndD...
Detail upload trace for file that fail to upload: build/Documentation/Sourcecode_11_08_2016.zip
Begin chunking upload file 'build/Documentation/Sourcecode_11_08_2016.zip', chunk size '4194304 Bytes', total chunks '8'.
Attempt '1' for uploading chunk '1' of file 'build/Documentation/Sourcecode_11_08_2016.zip'.
Generate new HttpRequest for uploading file 'build/Documentation/Sourcecode_11_08_2016.zip', chunk '1' of '8'.
Start uploading file 'build/Documentation/Sourcecode_11_08_2016.zip' to server, chunk '1'.
Chunk '1' attempt '1' of file 'build/Documentation/Sourcecode_11_08_2016.zip' fail to send request to server. Error: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Failure when receiving data from the peer    at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)    at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)    --- End of inner exception stack trace ---    at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d3.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Net.Http.HttpClient.<FinishSendAsync>d58.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Syste...
Backoff 9.606 seconds before attempt '2' chunk '1' of file 'build/Documentation/Sourcecode_11_08_2016.zip'.
Attempt '2' for uploading chunk '1' of file 'build/Documentation/Sourcecode_11_08_2016.zip'.
Generate new HttpRequest for uploading file 'build/Documentation/Sourcecode_11_08_2016.zip', chunk '1' of '8'.
Start uploading file 'build/Documentation/Sourcecode_11_08_2016.zip' to server, chunk '1'.
Finished upload chunk '1' of file 'build/Documentation/Sourcecode_11_08_2016.zip', elapsed 1965 (ms), response code 'Accepted'.
Attempt '1' for uploading chunk '2' of file 'build/Documentation/Sourcecode_11_08_2016.zip'.
Generate new HttpRequest for uploading file 'build/Documentation/Sourcecode_11_08_2016.zip', chunk '2' of '8'.
Start uploading file 'build/Documentation/Sourcecode_11_08_2016.zip' to server, chunk '2'.
Chunk '2' attempt '1' of file 'build/Documentation/Sourcecode_11_08_2016.zip' fail to send request to server. Error: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Failure when receiving data from the peer    at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)    at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)    --- End of inner exception stack trace ---    at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d3.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Net.Http.HttpClient.<FinishSendAsync>d58.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Syste...
Backoff 6.425 seconds before attempt '2' chunk '2' of file 'build/Documentation/Sourcecode_11_08_2016.zip'.
Attempt '2' for uploading chunk '2' of file 'build/Documentation/Sourcecode_11_08_2016.zip'.
Generate new HttpRequest for uploading file 'build/Documentation/Sourcecode_11_08_2016.zip', chunk '2' of '8'.
Start uploading file 'build/Documentation/Sourcecode_11_08_2016.zip' to server, chunk '2'.
Chunk '2' attempt '2' of file 'build/Documentation/Sourcecode_11_08_2016.zip' fail to send request to server. Error: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Failure when receiving data from the peer    at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)    at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)    --- End of inner exception stack trace ---    at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d3.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Net.Http.HttpClient.<FinishSendAsync>d58.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Syste...
Backoff 9.446 seconds before attempt '3' chunk '2' of file 'build/Documentation/Sourcecode_11_08_2016.zip'.
Attempt '3' for uploading chunk '2' of file 'build/Documentation/Sourcecode_11_08_2016.zip'.
Generate new HttpRequest for uploading file 'build/Documentation/Sourcecode_11_08_2016.zip', chunk '2' of '8'.
Start uploading file 'build/Documentation/Sourcecode_11_08_2016.zip' to server, chunk '2'.
4 files failed to upload, retry these files after a minute.
Retry file upload after 60 seconds.

**Comment by cornillemichiel** [comment] 2017-04-25 10:15
I'm having a similar issues since yesterday with the publish artifact drop step, ... http://stackoverflow.com/questions/43604961/vsts-build-agent-issues-in-step-publish-artifact-drop
maybe there are server issues?

**Comment by bryanmacfarlane** [comment] 2017-04-25 12:01
There was a live site issue yesterday.  

I responded to the SO post.  Also, if you send account names I can check service side / LSIs.  If you don't want to post account info here then email me.  My email alias is bryanmac and that is at microsoft

**Comment by cornillemichiel** [comment] 2017-04-25 15:17
@bryanmacfarlane I can confirm that the issue still exists for us. I sent you an e-mail with a vsts link and log of an example failing publish step.

**Comment by cornillemichiel** [comment] 2017-04-26 13:09
@NielsWillems  are you on telenet ( Belgium)?

**Comment by NielsWillems** [comment] 2017-04-26 13:40
@cornillemichiel  Yep

**Comment by cornillemichiel** [comment] 2017-04-26 15:13
A little update: we are currently investigating why it won't work for us on telenet, but it does when using a @NielsWillems  belgacom fallback line, ill keep you updated.

**Comment by TingluoHuang** [comment] 2017-04-26 15:23
@cornillemichiel can you try upload something to Azure blob storage directly use VS or web portal?

**Comment by cornillemichiel** [comment] 2017-04-26 15:36
@TingluoHuang I uploaded an 85mb file using the azure portal to one of our blob storage containers and experienced no issues whatsoever.

**Comment by TingluoHuang** [comment] 2017-04-26 15:39
@cornillemichiel have you try upload that file multiple times? since when failure happened in upload build artifacts you also getting error randomly everytime.

**Comment by NielsWillems** [comment] 2017-04-26 15:42
Cheers @cornillemichiel !

**Comment by cornillemichiel** [comment] 2017-04-27 07:21
@TingluoHuang  Multiple uploads from azure portal to blob storage containers, tried different block sizes (100mb and 4mb) multiple files, tried uploading same file twice, tried uploading larger files, smaller files, ... no errors at all ...

**Comment by NielsWillems** [comment] 2017-04-27 10:03
@cornillemichiel  When using our Belgacom backup line it also worked.

**Comment by TingluoHuang** [comment] 2017-05-01 03:05
@NielsWillems @cornillemichiel are you guys still hitting the problem, i can't find anything useful from my side, does your local ISP give you and suggestion on the issue?

**Comment by cornillemichiel** [comment] 2017-05-03 13:51
@TingluoHuang  Is there any alternative publish artifact method we can use while we wait for an answer of our ISP? Maybe one that uses a different protocol?

**Comment by TingluoHuang** [comment] 2017-05-04 03:46
@cornillemichiel i don't think we have any other option, maybe just copy to Azure blob storage.
you might want to try this task:
https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/AzureFileCopy

**Comment by cornillemichiel** [comment] 2017-05-04 10:12
We found a temp. solution in using an internal file share for publishing. But this is of course not something we want in the future.

**Comment by deprouwn** [comment] 2017-05-10 15:54
@NielsWillems @cornillemichiel @TingluoHuang do you still have this issue? We also have the same problem with Telenet and don't have a Belgacom-backup line :(

**Comment by cornillemichiel** [comment] 2017-05-10 16:06
Yes. We are trying to get our support request escalated ...

**Comment by deprouwn** [comment] 2017-05-11 06:55
Hi @cornillemichiel, you escalated that to Telenet-support or to Microsoft?

**Comment by jtemperv** [comment] 2017-05-11 10:35
@deprouwn as I'm a colleague of @cornillemichiel , I can answer on that question: we are currently trying to escalate this at Telenet support. All additional logs and information are very welcome in order to support our case. 

We also have the problem in VSTS Release when we're trying to deploy our website with an Azure App Service Deploy step. The strange thing is that our "Test" environment deploy works, but our "Integration" environment always fails, even after deleting and recreating the App Service. Both environments use the same infrastructure layout and the same release step to deploy the app. @bryanmacfarlane  @TingluoHuang any ideas why that could happen? The error we get is: 

> 2017-05-10T07:58:33.8773259Z Warning: Retrying the sync because a socket error (10054) occurred.  

and then after 25 retries:

> 2017-05-10T07:59:04.6767179Z ##[error]Failed to deploy App Service.
> 2017-05-10T07:59:04.6767179Z ##[error]Error: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
> 2017-05-10T07:59:04.6767179Z Error: An existing connection was forcibly closed by the remote host
> 2017-05-10T07:59:04.6767179Z Error count: 1.

and:

> 2017-05-10T07:59:06.6454469Z ##[error]Error: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe failed with return code: 4294967295

**Comment by deprouwn** [comment] 2017-05-11 11:12
Hi @jtemperv 
For us it's something different, to publish build artificats. See the error in the attachment.
We'll try with a 3g-router to be sure if the Telenet-connection is the issue.

grtz,
Nico

![pasted image at 2017_05_10 05_21 pm](https://cloud.githubusercontent.com/assets/28602963/25946427/5b5cfbf0-364b-11e7-83d9-e4d48ba0e02e.png)

**Comment by jtemperv** [comment] 2017-05-11 11:45
@deprouwn we have issues with both:
- publishing artifacts
- deploying site

and even:
- restoring bacpac files to Azure SQL

**Comment by deprouwn** [comment] 2017-05-11 14:46
Hi @jtemperv,
with a 3g router we have no problem at all, so Telenet is definitely the issue. Do you have a Telenet-casenr for this we can refer to? Our case is 02102128. 
If we do a tracert on the ip, we have a different route (for ip 191.233.96.220)
thx,
Nico.

**Comment by SynetonOps** [comment] 2017-05-12 07:53
Hello, 

We've encountered same problems. Also Telenet customer and also **no fail** on backup VDSl line from Belgacom. (other ISP). So we did some tests.

1) Networksniff with wireshark: it seems there is some loss of TCP packets (see attachment)
2) Install  Buildagent on other Windows device with lower version of buildagent > same problem
3) Install Buildagent on MAC OSX > same problem , BUT, eventually the build succeeds. It seems te be related cuz there were a lot of extra retries.
4) Try proxyserver on Windows machine > same problem

So it surely seems it's a problem with Telenet. So we've contacted Telenet wit this case. They now ask us to do a traceroute on both lines. Telenet en backup VDSL .

Our Telenet ticket reference: 02102423.

This is all info i have at this moment.
<img width="1280" alt="tcp lost packets" src="https://cloud.githubusercontent.com/assets/28621157/25988265/a0df2e76-36f7-11e7-8686-a8f4009260f8.png">

**Comment by jtemperv** [comment] 2017-05-12 08:19
Hey,

I've asked our IT department for the case number. I'll post it here as soon as I get a reply from them.

Meanwhile, if anyone is interested in our tracert, here it is:

 ```
Tracing route to 191.233.96.220 over a maximum of 30 hops

 1    <1 ms    <1 ms    <1 ms  ***********[192.168.1.1]
  2     *        *        *     Request timed out.
  3     9 ms    10 ms    19 ms  d54C7C145.access.telenet.be [84.199.193.69]
  4    16 ms    19 ms    13 ms  dD5E0FEA9.access.telenet.be [213.224.254.169]
  5    13 ms    13 ms    19 ms  dD5E0FA75.access.telenet.be [213.224.250.117]
  6    17 ms    17 ms    13 ms  dD5E0FA23.access.telenet.be [213.224.250.35]
  7    17 ms    19 ms    15 ms  ae2-0.bru30-96cbe-1a.ntwk.msn.net [198.200.130.216]
  8    37 ms    36 ms    36 ms  ae5-0.amb-96cbe-1a.ntwk.msn.net [104.44.225.29]
  9    47 ms    38 ms    38 ms  be-71-0.ibr02.amb.ntwk.msn.net [104.44.9.136]
10    36 ms    39 ms    39 ms  ae75-0.ams04-96cbe-1b.ntwk.msn.net [104.44.9.239]
11     *        *        *     Request timed out.
12     *        *        *     Request timed out.
```

**Comment by SynetonOps** [comment] 2017-05-12 09:12
Update:
Test5: Build from other location but still Telenet ISP, no problem there. Tracert follows different hops then our Company's location. So it appears not to impact all Telenet customers and depends on the route taken.

More info when I have some.

**Comment by deprouwn** [comment] 2017-05-12 09:52
Thx a lot for the info, we'll give it a try with our backup soho Telenet line instead of the corporate-line.

**Comment by jtemperv** [comment] 2017-05-12 13:05
I received the Telenet case number from our IT department: 02102899

**Comment by jtemperv** [comment] 2017-05-16 09:18
Hi,

Telenet installed a patch and asked us to test this again, but we're still facing the same issue, larger zip files cannot upload. Can you guys please try it again and post your findings?

**Comment by SynetonOps** [comment] 2017-05-17 07:45
We have received same mail, but first impression is not conclusive, sometimes it works, sometimes it doesn't.
It seems there is improvement but not entirely fixed. Before we answer Telenet we will perform extra tests.
More info when i have some!

**Comment by SynetonOps** [comment] 2017-05-18 09:56
Yesterday and today , we've managed to release to Azure without any problems.
It seems that Telenet took care of the problem.
Hop it stays that way :)

**Comment by jtemperv** [comment] 2017-05-18 15:07
@SynetonOps Sadly enough, the problem occurred again today, so it's not completely solved. Sometimes it takes ages to publish the artifacts, e.g. 14 mins. Do you see the same behavior in publishing?

**Comment by TingluoHuang** [comment] 2017-06-02 18:43
do you guys still having problem with upload artifact? if not, i will close the issue.

**Comment by jtemperv** [comment] 2017-06-03 09:04
@TingluoHuang as this is clearly an ISP issue, you can close this case I think. There's nothing you can do on your end. Thanks for the support. 👍

**Closed** 2017-06-03 14:33 UTC
