### ISSUE TITLE
execute "az" command will exit with error "Fail to load or parse file /root/.azure/azureProfile.json"

### ISSUE THREAD

**Issue by michaeljqzq** [Microsoft/vsts-agent#1816] opened 2018-09-10 02:54 UTC
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 2.140.0

OS of the machine running the agent? Linux

## VSTS Type and Version
VisualStudio.com

If VisualStudio.com, what is your account name? http://zhqqitest.visualstudio.com

## What's not working?
I'm the author of this plugin [Azure IoT Edge For VSTS](https://marketplace.visualstudio.com/items?itemName=vsc-iot.iot-edge-build-deploy), and recently my customer reported that one of my task failed with the error message "Fail to load or parse file /root/.azure/azureProfile.json". I checked and found that
When executing az cli on build agent for example:
2018-09-10T02:26:53.5131871Z [command]/usr/bin/az login --service-principal -u *** -p *** --tenant ***
2018-09-10T02:27:01.1514627Z Fail to load or parse file /root/.azure/azureProfile.json. It is overridden by default settings.
2018-09-10T02:27:01.1538224Z [
2018-09-10T02:27:01.1554452Z Fail to load or parse file /root/.azure/az.json. It is overridden by default settings.
2018-09-10T02:27:01.1571907Z Fail to load or parse file /root/.azure/az.sess. It is overridden by default settings.

It will show some file is missing and cause the exit code of command set to non-zero. But this never happened before. I gave a work-around to add an Azure CLI task before to generate the missing files and the tasks in my extension can work. But is there a fix from your side? Thank you

**Comment by johlrich** [comment] 2018-09-10 21:07
Same exact problem here with a different task. I use [Terraforming (by AKC)](https://marketplace.visualstudio.com/items?itemName=ArkiaConsulting.terraform-extension)

Last successful build was on 2.139.1

For me this is a critical issue as all releases are currently blocked for me. Hosted Linux Agent with 2.140.0 on https://imaginedcloud.visualstudio.com

Is there a way to pin the hosted version to an agent still on 2.139.1? I tried putting an Agent.Version demand but it used -gtVersion in the history instead of exact.

**Comment by TingluoHuang** [comment] 2018-09-10 21:34
@michaeljqzq @johlrich the problem is not caused by the agent, it's a task bug. the updated version Azure CLI in the hosted image produce some STDERR on first launch and the task is not handle it correctly.
https://github.com/Microsoft/vsts-tasks/pull/8279

**Comment by johlrich** [comment] 2018-09-10 21:40
@TingluoHuang thanks for the detail. I will follow up with the task author and link them to it. 

Is there a way to pin the hosted agent's version so I can at least run on the 2.139.1 version until that happens?

**Comment by TingluoHuang** [comment] 2018-09-10 21:42
@johlrich pin back the agent version won't help, it's the image update that brings in the latest version Az cli cause the problem, and we don't have a way to pin back image update at this point. :(

**Comment by johlrich** [comment] 2018-09-10 21:55
@TingluoHuang ahhhh thanks for that important detail, I didn't realize that was a first run thing. Adding a task before that one to just call `az` has at least unblocked me until the task can be fixed.

**Comment by TingluoHuang** [comment] 2018-09-10 22:02
cool, thanks for sharing the workaround.

**Comment by TingluoHuang** [comment] 2018-09-11 13:33
i am going to close the issue since it's not an agent issue.

**Closed by TingluoHuang** 2018-09-11 13:33 UTC
