### ISSUE TITLE
Service Fabric Deployment Task fails for AAD deployments after release of 2.111.1 (Hosted Agent)

### ISSUE THREAD

**Issue by PlasticLizard** [Microsoft/vsts-agent#755] opened 2017-01-17 07:15 UTC
## **Agent version and platform**
Version of your agent? 2.111.1
<br>
OS of the machine running the agent? VSTS Hosted Agent (Windows?)
<br>
## **VSTS type and version**
VisualStudio.com
<br>

If VisualStudio.com, what is your account name? http://amghus.visualstudio.com
<br>
## **What's not working?** 

The latest update of the hosted agent, which seems to have been released on 1/13/2017, is causing the ServiceFabricDeploy task to fail on line 97 of Tasks/ServiceFabricDeploy/utilities.ps1:

$userCredential = Create-Object -TypeName Microsoft.IdentityModel.Clients.ActiveDirectory.UserCredential -ArgumentList @($authParams.Username, $authParams.Password)

With this error:

##[error]Cannot find an overload for "UserCredential" and the argument count: "2".

The failing Service Fabric Application Deployment task is version 1.2.1 and the failing agent version is 2.111.1

The last successful release in my environment was deploy task version 1.2.1 and the failing agent version is 2.110.0

So it looks like an incompatibility of some kind introduced in the agent since the exact same version of the Service Fabric Deployment task used to work on 2.110.0.

**Comment by ericsciple** [comment] 2017-01-18 02:24
@mthalman-msft fyi

**Comment by ericsciple** [comment] 2017-01-18 02:26
My guess is a regression in the task (or less likely a prereq on the machine?). The agent doesn't carry any dependencies for the task. Closing the issue here. Looks like an [issue is already open](https://github.com/Microsoft/vsts-tasks/issues/3434) on the tasks repo, which I think is the more appropriate for this issue.

**Closed by ericsciple** 2017-01-18 02:27 UTC
