### ISSUE TITLE
Variable reverts to original value after setting it from another task

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-agent#177] opened 2016-05-19 19:03 UTC
One of my users [reported the following issue](https://github.com/jessehouwing/vsts-variable-tasks/issues/11).

Steps to reproduce:
 - Install the latest version of the [VSTS variable tasks](https://marketplace.visualstudio.com/items?itemName=jessehouwing.jessehouwing-vsts-variable-tasks) 
 - On TFS 2015 u2.1 create a new build definition that is in line with: [setvariable.txt](https://github.com/Microsoft/vsts-agent/files/273232/setvariable.txt)
 - Queue a build, see that it ends with `cmd /c echo C1234`

Expected result:
 - Build ends with `cmd /c echo 1234`

It seems to be caused by the fact that the original variable has been defined as an unexpanded variable and it seems like the agent isn't (always) using the current value but expands the variable again from scratch.

The funny thing is that in the following setup the cmd task reads `C9` while the Set variable task that comes after it shows `9`. Is this an interaction issue between Powershell and Node? [setvariable3.txt](https://github.com/Microsoft/vsts-agent/files/273264/setvariable3.txt)

Diagnostic logs:
[worker_20160519-185515-utc_9352.txt](https://github.com/Microsoft/vsts-agent/files/273273/worker_20160519-185515-utc_9352.txt)
[agent_20160519-185523-utc.txt](https://github.com/Microsoft/vsts-agent/files/273274/agent_20160519-185523-utc.txt)

**Comment by jessehouwing** [comment] 2016-05-19 19:06
Agent 1.99 on Windows.

**Comment by ericsciple** [comment] 2016-05-24 18:08
Removing milestone. The reported issue is related to the old Windows agent (not this repo). Working through some other issues right now, I'll leave this open so I can understand and verify the functionality in this agent.

**Comment by ericsciple** [comment] 2016-05-24 21:58
The good news is that it's fixed in this new open source agent.

I was able to repro using the old closed source Windows agent. It looks like an issue with the execution handler that the Command Line task uses.

**Comment by ericsciple** [comment] 2016-05-25 00:58
I was able to workaround the issue by using %myvar% in the Command Line task instead of $(myvar).

I'm going to go ahead and close the issue since it isn't an issue with *this agent* (i.e this repo).

FYI - The way I reproduced the error was:
 * Set a variable on the definition `myvar` to `originalvalue`
 * From a task built on the PowerShell execution handler:
```powershell
write-host "Current myvar=$env:myvar"
write-host "Appending .FromTaskWithPowerShellExecutionHandler"
write-host "##vso[task.setvariable variable=myvar]$env:myvar.FromTaskWithPowerShellExecutionHandler"
write-host "Done"
```
 * From a task with a Node execution handler:
```js
console.log('Current myvar=' + process.env['myvar']);
console.log('Appending .FromTaskWithNodeExecutionHandler');
console.log("##vso[task.setvariable variable=myvar]" + process.env['myvar'] + '.FromTaskWithNodeExecutionHandler');
console.log('Done');
```
 * Add a Command Line task `echo` with arguments `myvar=$(myvar)`. The output reads: `myvar=originalvalue`

Again, I was able to workaround this by changing the Command Line arguments to `myvar=%myvar%`. The output then reads: `myvar=originalvalue.FromTaskWithPowerShellExecutionHandler.FromTaskWithNodeExecutionHandler`

**Closed by ericsciple** 2016-05-25 00:58 UTC
Labels: bug

**Comment by jessehouwing** [comment] 2016-05-25 05:35
Where/how can we report the issue to gets to fixed in the old windows
agent?

**Comment by ericsciple** [comment] 2016-05-25 16:35
This agent is replacing that one.

**Comment by bryanmacfarlane** [comment] 2016-05-25 16:59
For VSTS and windows, sooner.  For on-prem and windows, next major release of TFS
