### ISSUE TITLE
Agent can't connect behind the corporate proxy (libcurl version is too old on Redhat)

### ISSUE THREAD

**Issue by peterg-ra** [Microsoft/vsts-agent#908] opened 2017-04-07 10:31 UTC
## **Have you try trouble shooting doc?**
Yes, nothing works

## **Agent version and platform**
2.111.1
2.115.0
<br>
OS of the machine running the agent?
RedHat Enterprise Linux 7.3
<br>
## **VSTS type and version**
VisualStudio.com
<br>

If VisualStudio.com, what is your account name?
Prefer not to share.
<br>
## **What's not working?** 

We are trying to make the TFS agent work behind a corporate proxy (McAfee Web Gateway 7.6.1.1.0.21006).

There is IP based authentication bypass enabled for the following URLs following https://msdn.microsoft.com/en-us/library/mt604698.aspx:

https://management.core.windows.net
https://app.vssps.visualstudio.com
https://login.microsoftonline.com
https://login.live.com
https://go.microsoft.com
https://graph.windows.net
https://app.vsspsext.visualstudio.com

and our visualstudio endpoint of course.

We have some cloud servers without proxy, they work just fine with the same agent version.

TFS agents version 2.111.1 and 2.115 have the same problem.

The proxy's name is in the .proxy file, no whitespaces there at all.

Tried to add the proxy's cert to the NSS cert chain to no effect.

The HTTP trace showing that it does not try to connect to any other URLs, it just fails after establishing the connection to the VSTS endpoint.

I can provide tcpdump output if that helps.

Auth is PAT, definitely working on other installations.

curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.21 Basic ECC zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets

curl-7.29.0-35.el7.x86_64
libcurl-7.29.0-35.el7.x86_64

<br>
## **Agent and Worker's diag log**

[2017-04-07 10:13:48Z ERR  Terminal] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Failure when receiving data from the peer
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__43`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider.<TestConnectionAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__7.MoveNext()

Your help is very much appreciated!

**Comment by Dan-Co** [comment] 2017-04-11 10:26
An update on this..

This definitely seems Red Hat related only.
We can confirm that both Windows and Ubuntu agents work fine behind the proxy firewall.

The version of libcurl is a lot lower on RHEL but is the latest available in the core repo, so we are not wantin gto upgrade this manually as there are no official sources.

Hopefully someone can assist here?

**Comment by TingluoHuang** [comment] 2017-04-11 13:59
@Dan-Co you can try setup a test Redhat box with Latest libcurl that build from source code just for testing?

**Comment by Dan-Co** [comment] 2017-04-11 15:57
Hi @TingluoHuang - yes I can confirm that an updated libcurl does indeed work (I didnt create from source though at this time).

However official RHEL version is 7.29, and we can definitely still use curl form the command line behind the same proxy - so something in the way the VSTS agent uses curl is at fault?

VSTS agent officially supports RHEL so we are hoping that we can get a fix for this that doesnt break our RHEL upgrade process because we have hacked about with curl and its dependencies.

**Comment by TingluoHuang** [comment] 2017-04-11 16:22
@Dan-Co the agent is built on dotnet core, looks like dotnet core require newer version libcurl.
https://github.com/dotnet/corefx/issues/14614

**Comment by ericsciple** [comment] 2017-04-12 02:32
@TingluoHuang is this something we should attempt to detect (is it feasible and practical)? if not, should we add to troubleshooting?

**Comment by TingluoHuang** [comment] 2017-04-13 19:42
https://github.com/dotnet/corefx/issues/18328
https://bugzilla.redhat.com/show_bug.cgi?id=1442220

**Closed** 2018-01-22 21:08 UTC
