### ISSUE TITLE
VSTS agent can no longer access Jenkins artifacts

### ISSUE THREAD

**Issue by JacobHenner** [Microsoft/vsts-agent#1037] opened 2017-06-27 13:34 UTC
## **Have you try trouble shooting doc?**
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting

## **Agent version and platform**
Version of your agent? 2.119.1
<br>
OS of the machine running the agent? Windows 2012 R2
<br>
## **VSTS type and version**
VisualStudio.com
If VisualStudio.com, what is your account name? http://msusa-poc.visualstudio.com
<br>
## **What's not working?** 
Since upgrading agents to 2.119.1, VSTS is no longer able to retrieve artifacts from Jenkins. The process worked properly using 2.115, and only started failing upon upgrade. After reverting back to 2.115, the error disappears.

It looks like part of 30925e3048095ca1992d8e439076d6d7d942c81a broke the connection between the agent and Jenkins. When I try to run a release, I get the following error:

> 2017-06-26T15:30:45.4280884Z BuildId: 98
> 
> 2017-06-26T15:30:49.8165979Z An error occurred during download: Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.ArtifactDownloadException: Jenkins build 98 is invalid.
> 
>    at Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.JenkinsArtifact.<DownloadAsync>d__15.MoveNext()
> 
> --- End of stack trace from previous location where exception was thrown ---
> 
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> 
>    at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.<>c__DisplayClass34_2.<<DownloadArtifacts>b__2>d.MoveNext()
> 
> --- End of stack trace from previous location where exception was thrown ---
> 
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> 
>    at Microsoft.VisualStudio.Services.Agent.Worker.Release.RetryExecutor.<ExecuteAsync>d__20.MoveNext()
> 
> 2017-06-26T15:30:49.8478672Z ##[error]Jenkins build 98 is invalid.
> 
> 2017-06-26T15:30:49.8478672Z ##[section]Finishing: Download Artifacts

I've turned on HTTP debugging, and I see that the VSTS agent is receiving a 403 when it attempts to connect to Jenkins. No settings on Jenkins have been changed. 

Please let me know if additional information is required. 

Regards, 
Jacob Henner

**Comment by TingluoHuang** [comment] 2017-06-27 13:45
@GitHubSriramB @kasubram  can you guys take a look at this?

**Comment by JacobHenner** [comment] 2017-06-27 13:54
@TingluoHuang Would you like me to submit a report through the VSTS feedback feature too, or will this suffice?

**Comment by TingluoHuang** [comment] 2017-06-27 14:00
@JacobHenner  i think here should be fine for any agent related issue. :)

**Comment by kasubram** [comment] 2017-06-28 19:35
The correct commits which cause this issue is [this](https://github.com/Microsoft/vsts-agent/commit/7b06e5e9956c570a796842d596a898438ce29e5a) and [this](https://github.com/Microsoft/vsts-agent/commit/33fe635951440c1ee51678365a155d00c9905471)

We made a change in the first commit, where if there is no artifact found in the build we will add a warning in the release summary but not fail the release itself. We have a more ongrowing scenario where customers don't have an artifact in the build but still wanted to use the build for CI (azure/docker related tasks are a good example for such scenario)
 
But this caused an issue with Jenkins, it always succeeded even if the build does not exists since we only check for artifacts using the below api 
> http://{SERVER}/job/{JobName}/{JobID}/artifact/*zip*/archive.zip
Hence we made an additional check to verify if the build really exists. Thats where its failing for you now.

If you are getting 403 when accessing the build, wouldn't you be getting the same when trying to download the artifact as well?
When you use the old agent, what is the HTTP response you get when artifact is getting downloaded?

**Comment by JacobHenner** [comment] 2017-06-28 20:19
@kasubram I assume the response is a 200, since the artifact is successfully downloaded and displayed within VSTS.

**Comment by GitHubSriramB** [comment] 2017-06-29 13:01
@JacobHenner - is the credentials to connect to Jenkins server still valid? Wondering 403 is due to the credentials being invalid.

**Comment by JacobHenner** [comment] 2017-06-29 14:07
Yes. When I revert to 2.115, the same credentials work fine.

Regards,

Jacob Henner

This message was sent on the go.

**Comment by kasubram** [comment] 2017-07-07 09:11
I can't reproduce this, other alternative I can think of is instead of calling job API
`http://{SERVER}/job/{JobName}/{JobID}`
probably we should call the artifact api to see if it exists.
`http://{SERVER}/job/{JobName}/{JobID}/artifact`

**Comment by JacobHenner** [comment] 2017-07-07 12:48
@kasubram I've determined the cause of the issue. 

From https://www.visualstudio.com/en-us/docs/build/actions/agents/v2-windows#how-do-i-configure-the-agent-to-work-through-a-web-proxy-and-connect-to-team-services:

> This procedure enables the agent infrastructure to operate behind a web proxy. Your build definition and scripts must still handle proxy configuration for each task and tool you run in your build. For example, if you are using a task that makes a REST API call, you must configure the proxy for that task.

However, in change e31a02c63215501daf573e87329b69f44f2933a4, JenkinsArtifact.cs was modified to use the proxy specified for VSTS’s connection to visualstudio.com. Unfortunately, internal hosts (Jenkins) are not accessible through our corporate proxy, so the proxy returns an error to the VSTS agent and the deployment fails.

A few months back, we were told that a host-based proxy exemption feature was scheduled to be included in VSTS. Do you have an updated timeline for this feature? If not, can there at least be an option to use or not use the proxy when the user configures his/her connection to Jenkins?

**Comment by bryanmacfarlane** [comment] 2017-07-09 21:56
@TingluoHuang - Remember to create feature for 120 and docs

**Comment by GitHubSriramB** [comment] 2017-07-10 06:48
@bryanmacfarlane, @TingluoHuang - Given this is not related to the Jenkins API we are calling, we don't need the fix suggested by @kasubram 

Assigning this issue to you to take it forward.

**Comment by TingluoHuang** [comment] 2017-08-10 01:33
@JacobHenner I guess i can close this since 2.120.1 has been released. let me know if you need more help.

**Closed by TingluoHuang** 2017-08-10 01:33 UTC
