### ISSUE TITLE
Nuget.exe in vsts agent needs to be updated to v3.4.4

### ISSUE THREAD

**Issue by camp-007** [Microsoft/vsts-agent#613] opened 2016-09-27 05:47 UTC
## **Agent version and platform**
Version of your agent? 2.107
<br>
OS of the machine running the agent? Windows
<br>
## **VSTS type and version**
VisualStudio.com
<br>
## **What's not working?** 
When trying to run the nuget packager step using the "Include referenced projects" option, if your project has dependencies on other nuget packages that target .NET Standard, then the nuget.exe pack command will fail.  I checked the nuget.exe version included with the build agent and it is running v3.3.  If I override the nuget packager 'path to nuget.exe' property and set it to a version of nuget that is v3.4.4, then the package step will succeed.

I can only assume that you need the latest version of nuget to fully support all the .NET Standard scenarios.

What is the process for updating the external\nuget\nuget.exe version?  Should the build agent automatically update that?  Is there a timeframe for updating to the latest?  Is it safe to manually update the external\nuget\nuget.exe file myself?

**Comment by bryanmacfarlane** [comment] 2016-09-27 10:31
Duplicate of https://github.com/Microsoft/vsts-agent/issues/582

Has the details

**Closed by bryanmacfarlane** 2016-09-27 10:31 UTC
