### ISSUE TITLE
Error during run config.sh

### ISSUE THREAD

**Issue by FRIDIE** [Microsoft/vsts-agent#238] opened 2016-06-03 14:19 UTC
After starting the config i getting this part. 

./config.sh
>> EulasSectionHeader:
TeeEula
Prompt0Default1 > 

Here are the Info from the Log File:

[2016-06-03 14:14:01Z INFO AgentProcess] Agent is built for OSX - osx.10.11-x64.
[2016-06-03 14:14:01Z INFO AgentProcess] RuntimeInformation: Darwin 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64.
[2016-06-03 14:14:01Z INFO AgentProcess] Version: 2.101.1
...
[2016-06-03 14:14:01Z INFO CommandSettings] Flag 'help': 'False'
[2016-06-03 14:14:01Z INFO CommandSettings] Flag 'version': 'False'
[2016-06-03 14:14:01Z INFO CommandSettings] Flag 'commit': 'False'
[2016-06-03 14:14:01Z INFO CommandSettings] Command 'unconfigure': 'False'
[2016-06-03 14:14:01Z INFO CommandSettings] Command 'run': 'False'
[2016-06-03 14:14:01Z INFO CommandSettings] Command 'configure': 'True'
[2016-06-03 14:14:01Z INFO ConfigurationManager] ConfigureAsync
[2016-06-03 14:14:01Z INFO ConfigurationStore] IsConfigured()
[2016-06-03 14:14:01Z INFO ConfigurationStore] IsConfigured: False
[2016-06-03 14:14:01Z INFO ConfigurationManager] Is configured: False
[2016-06-03 14:14:01Z INFO Terminal] WRITE LINE: 
[2016-06-03 14:14:01Z INFO Terminal] WRITE LINE: >> EulasSectionHeader:
[2016-06-03 14:14:01Z INFO Terminal] WRITE LINE: 
[2016-06-03 14:14:01Z INFO Terminal] WRITE LINE: TeeEula
[2016-06-03 14:14:01Z INFO Terminal] WRITE LINE: 
[2016-06-03 14:14:01Z INFO CommandSettings] Flag 'acceptteeeula': 'False'
[2016-06-03 14:14:01Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-06-03 14:14:01Z INFO PromptManager] ReadValue
[2016-06-03 14:14:01Z INFO Terminal] WRITE: Prompt0Default1 > 
[2016-06-03 14:14:01Z INFO Terminal] READ LINE

**Comment by ericsciple** [comment] 2016-06-04 02:20
Duplicate of https://github.com/Microsoft/vsts-agent/issues/225

See the duplicate issue for a workaround.

**Closed by ericsciple** 2016-06-04 02:20 UTC
