### ISSUE TITLE
Build does not use VS2017 despite the fact the agent has the capabilities

### ISSUE THREAD

**Issue by kfrajtak** [Microsoft/vsts-agent#1404] opened 2018-02-07 17:27 UTC
## Agent version and platform
2.129.0

## OS of the machine running the agent? 
Windows

## VSTS type and version
On-Prem TFS
Version 15.112.26307.0

## What's not working?
Build fails because MSBuild 14.0 (c:\Program Files (x86)\MSBuild\14.0\bin\msbuild) is used and the source code contains C# language elements only Roslyn compiler can understand. The agent can detect VS2017 and show it in the capabilities, but during the build, it fails to use it.

    ##[warning]Visual Studio version '15.0' not found. Looking for the latest version.

## Agent and Worker's diag log
````
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT: Getting latest Visual Studio 15 setup instance.
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT: & C:\Agent\bin\powershell\CapabilityHelpers\..\..\..\externals\vswhere\vswhere.exe -version '[15.0,16.0)' -latest -format json
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT: [
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT:   {
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT:     "instanceId": "a7fe9ac4",
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT:     "installDate": "2017-05-28T17:48:02Z",
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT:     "installationName": "VisualStudio/15.5.6+27130.2027",
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT:     "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise",
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT:     "installationVersion": "15.5.27130.2027",
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT:     "displayName": "Visual Studio Enterprise 2017",
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT:     "description": "...",
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT:     "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT:     "channelId": "VisualStudio.15.Release",
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT:     "channelPath": "C:\\Users\\BuildServer\\AppData\\Local\\Microsoft\\VisualStudio\\Packages\\_Channels\\4CB340F5\\catalog.json",
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT:     "channelUri": "https://aka.ms/vs/15/release/channel",
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT:     "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660692#15.5.6",
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT:     "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660708"
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT:   }
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT: ]
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT: Exit code: 0
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT: Testing leaf: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe'
[2018-02-07 15:30:45Z INFO PowerShellCapabilitiesProvider] STDOUT: Exists.
````

Thanks for help 

For now, I'll work around it with PS and call MSBuild of required version explicitly.

**Comment by bryanmacfarlane** [comment] 2018-02-12 21:58
This is fixed in a later version of the agent.  It's fine to use later versions against your TFS2017 server.  VS2017 installer and how to detect changed.

**Comment by bryanmacfarlane** [comment] 2018-02-12 21:58
Actually the issue is in the task - not an agent issue.  I'll add link ...

**Comment by bryanmacfarlane** [comment] 2018-02-12 22:00
https://github.com/Microsoft/vsts-tasks/releases/tag/VSBuild_dev15tfsu2rtw

**Comment by bryanmacfarlane** [comment] 2018-02-12 22:01
re-open in the vsts-tasks repo if that doesn't solve your issue

**Closed by bryanmacfarlane** 2018-02-12 22:01 UTC

**Comment by kfrajtak** [comment] 2018-02-13 07:39
Cool, thanks. I'll let you know.
