### ISSUE TITLE
Redhat 7.2 run as svc doesn't work if account not specified - Folder access permission

### ISSUE THREAD

**Issue by lydiakheng** [Microsoft/vsts-agent#572] opened 2016-09-02 22:10 UTC
## **Agent version and platform**

Version of your agent? 2.104.1
<br>
OS of the machine running the agent? Linux
<br>
## **VSTS type and version**

VisualStudio.com or On-Prem TFS? On-Prem TFS
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2? On prem TFS 2015 Update 3
<br>
If VisualStudio.com, what is your account name? http://account.visualstudio.com
<br>
## **What's not working?**

I noticed that agent 2.104.1 is running under the root which causing the _work folder has permission only for root. Unlike the older agent which running under a specific user account (not root). We have a script that running ssh command which it has to be under specific account so if it is root it will give the 
 "Permission denied, please try again." error.
Is it possible to have agent 2.104.1 to run under a specific user ?
# agent 2.104.1

[tfsagent@phx10ltfsap5001 myagent2]$ pwd
/home/tfsagent/myagent2
[tfsagent@phx10ltfsap5001 myagent2]$ ls -ltr
total 56256
-rwxr-xr-x  1 tfsagent tfsagent      225 Jul 28 11:51 run.sh
-rwxr-xr-x  1 tfsagent tfsagent      608 Jul 28 11:51 env.sh
-rwxr-xr-x  1 tfsagent tfsagent      309 Jul 28 11:51 config.sh
drwxr-xr-x  5 tfsagent tfsagent     4096 Jul 28 11:51 externals
-rw-rw-r--  1 tfsagent tfsagent 57560579 Aug  2 12:47 vsts-agent-rhel.7.2-x64-2.104.1.tar.gz
-rwxr-xr-x  1 tfsagent tfsagent     3672 Aug  2 12:50 svc.sh
drwxr-xr-x 13 tfsagent tfsagent    12288 Aug  2 12:53 bin
-rwxr-xr-x  1 root     root          560 Aug  2 12:53 runsvc.sh
**drwxr-xr-x 13 root     root         4096 Aug  8 16:00 _work**
drwxrwxr-x  3 tfsagent tfsagent     4096 Aug  8 16:03 _diag
# agent 1.999.0

[tfsagent@phx10ltfsap5001 myagent]$ pwd
/home/tfsagent/myagent
[tfsagent@phx10ltfsap5001 myagent]$ ls -ltr
total 98632
drwxrwxr-x  6 tfsagent tfsagent     4096 Jan 21  2016 node-v4.2.6-linux-x64
drwxrwxr-x  6 tfsagent tfsagent     4096 Feb  9 09:15 node-v5.6.0-linux-x64
drwxrwxr-x  2 tfsagent tfsagent     4096 Feb 11 12:23 _install
-rw-rw-r--  1 tfsagent tfsagent     4402 Mar 15 12:23 npm-debug.log
-rw-rw-r--  1 tfsagent tfsagent     1970 Mar 15 13:40 env.agent
drwxr-xr-x  5 tfsagent tfsagent     4096 Apr  6 14:53 xplat0.6.3Linux64
-rw-rw-r--  1 tfsagent tfsagent     4790 Apr 15 10:08 bluecoat.txt
-rwxr-xr-x  1 tfsagent tfsagent 19087074 Apr 15 10:16 TEE-CLC-14.0.3.zip
drwxrwxr-x  5 tfsagent tfsagent     4096 Apr 15 10:22 TEE-CLC-14.0.3
-rw-rw-r--  1 tfsagent tfsagent 12243729 Apr 15 11:29 node-v5.6.0-linux-x64.tar.gz
-rw-rw-r--  1 tfsagent tfsagent     4806 Apr 15 11:29 TEE-CLC-14.0.2-private.zip
drwxrwxr-x  4 tfsagent tfsagent     4096 Apr 15 11:30 runtime
drwxrwxr-x  3 tfsagent tfsagent     4096 Apr 15 11:30 _installer
drwxrwxr-x  6 tfsagent tfsagent     4096 Apr 15 11:30 agent
-rwxrwxrwx  1 tfsagent tfsagent     5707 Apr 15 11:30 getagent.sh
-rwxr-xr-x  1 tfsagent tfsagent 69550592 Apr 15 11:56 xplat0.6.3Linux64.tar.gz
-rwxrwxrwx  1 tfsagent tfsagent      160 Apr 15 12:08 configure.sh
-rw-rw-r--  1 tfsagent tfsagent     1518 Apr 15 12:08 package.json
-rw-r--r--  1 tfsagent tfsagent     1238 Apr 15 12:09 README.md
drwxrwxr-x 58 tfsagent tfsagent     4096 Apr 15 12:09 node_modules
drwxrwxrwx  2 tfsagent tfsagent     4096 Jul  1 13:24 logs
-rw-------  1 tfsagent tfsagent      175 Jul  1 13:45 nohup.out
-rwxrwxrwx  1 tfsagent tfsagent       62 Jul  1 13:46 run.sh
drwxrwxr-x  4 tfsagent tfsagent     4096 Jul 22 14:53 Testing
drwxrwxr-x  2 tfsagent tfsagent     4096 Aug  3 16:41 _diag
**drwxrwxr-x 17 tfsagent tfsagent     4096 Aug  4 16:18 _work**

<br>
## **Agent and Worker's diag log**

Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here. 
Unable to attach the logs file here. It keeps saying "Unfortunately, we don’t support that file type" I tried to attach a zip file.

**Comment by bryanmacfarlane** [comment] 2016-09-02 23:07
We do not run anything as root or elevate to root.  It sounds like you configured as root or ran a script as root.

We need you to specify the steps take from download, how you configured etc...

I cannot repro this per our instructions.

**Comment by bryanmacfarlane** [comment] 2016-09-03 15:40
>> Is it possible to have agent 2.104.1 to run under a specific user ?

This is the only mode we support.  Two scenarios:

Interactive:  Run interactive per instructions as the logged on user.  We actually even prevent running as root.

As a service:  See the service instructions.  It defaults to running the service as the logged on user but /svc.sh also takes an argument which is the user to run as.  It also prevents you running as root.

**Comment by bryanmacfarlane** [comment] 2016-09-07 11:41
I still can't repro this when I follow our instructions.  Your repro steps only include pwd and ls after config.  Not the actual config steps itself.

Reactivate when you can add repro steps.

**Comment by ccollins1973** [comment] 2016-09-27 22:40
Bryan, the _diag folder and the drop folder containing the build artifacts both were owned by root and unwritable.  We only used root/sudo privileges with we executed the svc.sh install command.  We did notice that there was a user=<blank> line in the cfg file created by the systemctl command.  This might be an issue caused by not providing the service_account user during the install.  Had I done "svc.sh install service_account", this problem might not have occurred.   In any case, the instructions for installing the service should note the syntax "svc.sh install <service account>" so we can run it correctly the first time. Thx, Chris

**Comment by bryanmacfarlane** [comment] 2016-09-27 22:41
@ccollins1973 - which OS.  Redhat?

**Comment by ccollins1973** [comment] 2016-09-27 22:44
Correct.  We only use RHEL now, and this agent was version v7.2.  Thx

**Comment by bryanmacfarlane** [comment] 2016-09-27 22:44
OK.  Assigned to me and we'll fix.  Thanks for reporting.

**Comment by ccollins1973** [comment] 2016-09-27 22:45
Awesome, thanks!

**Closed** 2018-06-28 15:12 UTC
Labels: bug

**Comment by ccollins1973** [comment] 2018-06-29 22:32
New sh script looks perfect, thanks for following up with this.
