### ISSUE TITLE
Custom capabilities scanner are discarded by auto update.

### ISSUE THREAD

**Issue by williambernardet** [Microsoft/vsts-agent#1811] opened 2018-09-06 16:59 UTC
## Have you tried trouble shooting?
Yes, we disabled the auto updating.

## Agent Version and Platform
Version of your agent? 2.136.1.

OS of the machine running the agent? Windows

## VSTS Type and Version
msftdevicesuat.VisualStudio.com

## What's not working?
We are currently adding custom capabilities scanner under <agent>/bin/powershell to automatically discover additional tools. The issue is that automatic update replaces the bin folder with newest one, and discard our changes. 

Currently the auto update has been disabled on agent side to workaround the issue, but this forces us to update the agent in manual way.
Would it be possible to either enable a post-update script to allow custom deployment operation (e.g: <agent>/user-post-update.ps1), or at least allow the Add-Capabilities.ps1 script to scan a custom location (e.g: <agent>/_usercapabilities).

## Agent and Worker's Diagnostic Logs
N/A
## Related Repositories
N/A

**Comment by TingluoHuang** [comment] 2018-09-06 17:16
@williambernardet I don't think we ever support adding customer capability discover script, it might be a reasonable feature, but not sure when we will do that. As alternative, you can create a `.env` file under agent root directory and add key value pair to it, those information will be upload as capability.
Ex:   `.env` file
```
foo=bar
mytool=exist
somekey=somevalue
```

**Comment by TingluoHuang** [comment] 2018-09-11 13:34
i am going to close this issue as by design for now, let me know if the workaround i provide is not working for you. :)

**Closed by TingluoHuang** 2018-09-11 13:34 UTC

**Comment by williambernardet** [comment] 2018-09-19 18:02
This work around is not enough for us, as we would like to have the capabilities refreshed each time we restart the agent, e.g we added some compiler.
Would this change be acceptable?
https://github.com/williambernardet/vsts-agent/blob/master/src/Misc/layoutbin/powershell/Add-Capabilities.ps1#L12
So user could have their own scanner in an insulated folder. This would be a nice improvement.
