### ISSUE TITLE
Windows: Y as service not running as admin, find out too late (after configured)

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-agent#330] opened 2016-06-24 17:31 UTC
## **Agent version and platform**
Version of your agent? 2.102.0
<br>
OS of the machine running the agent? win10
<br>
## **VSTS type and version**
VisualStudio.com?
If VisualStudio.com, what is your account name? http://jessehouwing-dev.visualstudio.com
<br>
## **What's not working?** 
I tried configuring the agent, but wasn't running as admin. The service installation failed (of course). Early warning would have been nice. But now the config script says "already configured".

![image](https://cloud.githubusercontent.com/assets/4173387/16346153/25bdf320-3a46-11e6-8c92-c39015f8f87f.png)

<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here. 

[Agent_20160624-172119-utc.txt](https://github.com/Microsoft/vsts-agent/files/332191/Agent_20160624-172119-utc.txt)
[Agent_20160624-172147-utc.txt](https://github.com/Microsoft/vsts-agent/files/332192/Agent_20160624-172147-utc.txt)

**Comment by jessehouwing** [comment] 2016-06-24 17:58
Deleting the following files allows me to reconfigure

![image](https://cloud.githubusercontent.com/assets/4173387/16346140/0efe3e60-3a46-11e6-889b-9bf8493bce42.png)

**Comment by bryanmacfarlane** [comment] 2016-06-24 18:11
There's a command to unconfigure.  I believe it's ./config.cmd remove

Does what you just did

**Comment by bryanmacfarlane** [comment] 2016-06-24 18:12
Documented here.

https://github.com/Microsoft/vsts-agent/blob/master/docs/start/moreconfig.md

We did remove so it's a clean shutdown of service and clean up for reconfig.

So as designed.

**Comment by jessehouwing** [comment] 2016-06-24 18:31
When the configuration fails, should it not automatically revert by calling remove? Or at least tell me the existence of the remove command to help me along?

**Comment by bryanmacfarlane** [comment] 2016-06-24 20:37
We can consider that (best effort cleanup on fail).

**Comment by bryanmacfarlane** [comment] 2016-06-24 20:40
Actually, configuration didn't fail.  It won't write if config fails.  Its' configured at that point - just configuring as a service didn't succeed.  I think what we need is if you answer yes to run as a service, check is admin up front.

On linux/osx side, I split config and run as a svc into two different invocations for some of these reasons.  (run as sudo because you might answer Y later ...).

We'll discuss

**Comment by TingluoHuang** [comment] 2016-09-02 02:42
I think we already fix this, we error out as long as you type 'Yes' to config as service in non-admin command prompt.
Close this for now, reopen if you hit it again.

**Closed by TingluoHuang** 2016-09-02 02:42 UTC
