### ISSUE TITLE
Exported YAML not valid for powershell task

### ISSUE THREAD

**Issue by simonvane** [Microsoft/vsts-agent#1675] opened 2018-07-06 15:22 UTC
## Have you tried trouble shooting?
yes

## Agent Version and Platform
Hosted VS2017

## VSTS Type and Version
VisualStudio.com 

## What's not working?
When build definition is exported using "View YAML" the following was included:

```
- powershell: . 'Deploy/BuildBase.ps1' true 
```

There are no arguments specified in the UI. I think it should have been:

```
- powershell: 'Deploy/BuildBase.ps1'
```

**Comment by TingluoHuang** [comment] 2018-07-06 15:24
@mireillehanna FYI,

**Comment by simonvane** [comment] 2018-07-06 15:41
Thanks @ericsciple. I have it working without the leading dot. Should I be adding that back in? What is it's purpose?

**Comment by ericsciple** [comment] 2018-07-06 15:53
Oh sorry, I misread the syntax. Without the leading dot works in your case.

We use it to dot source the file, so we can wrap the file name in a string and avoid quoting problems.

I'm still confused where the `true` is coming from. Can you provide a screenshot of your inputs in the designer definition?

**Comment by simonvane** [comment] 2018-07-07 05:47
Thanks @ericsciple, here's a screenshot.

![capture](https://user-images.githubusercontent.com/1423185/42407308-8ec54378-81b1-11e8-9396-3b525415820b.PNG)

**Comment by ericsciple** [comment] 2018-07-07 06:37
Thanks, I confirmed this reproduces on master. I opened a bug internally and assigned it to the appropriate team. I'm closing the work item here since the View Yaml bugs aren't tracked in this repo.

**Closed** 2018-07-07 06:37 UTC
Labels: Area: YAML

**Comment by simonvane** [comment] 2018-07-07 07:05
Thanks @ericsciple. Which repo should I be looking at for "View YAML"

**Comment by ericsciple** [comment] 2018-07-07 07:21
It's a private repo. Opening the issue here was useful, and I'm glad you did, since a bug is assigned to the correct engineer now. This repo is really for the agent, but we've blurred the lines a bit since this is the closest matching public repo for yaml communication. Technically the agent doesn't know anything about yaml. When a build is queued, the server compiles the yaml into same `plan` format that designer definitions use. By the time a `job` gets assigned to an agent, the agent has no idea whether the plan was from a yaml definition or designer definition. We track some yaml bugs here, since many of the docs are temporarily here. It's a convenient place for public feedback.
