### ISSUE TITLE
nuget version needs to be v4

### ISSUE THREAD

**Issue by JohnGalt1717** [Microsoft/vsts-agent#873] opened 2017-03-22 17:24 UTC
Given that pretty much anything you generate with VS.net 2017 and thus hosted2017 will require nuget v4 this should have been updated long ago to support v4 as an option (and be the default)

**Comment by bryanmacfarlane** [comment] 2017-03-22 20:04
Dupe of https://github.com/Microsoft/vsts-tasks/issues/3756 

Should affect net core scenarios.

Not an agent issue.  It's the nuget task that's offering v4.  Tasks are in that repo.

The packaging team just checked that in so it should in the VSTS next rollout

https://github.com/Microsoft/vsts-tasks/commit/3e3ec62b228f934181170aa58fd41b94a58d1956

**Closed by bryanmacfarlane** 2017-03-22 20:04 UTC
