### ISSUE TITLE
Multiple agents with 'runasautologon' feature

### ISSUE THREAD

**Issue by Virenta** [Microsoft/vsts-agent#1482] opened 2018-03-29 11:55 UTC
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 2.129.0

OS of the machine running the agent? Windows Server 2012 R2

## VSTS Type and Version
On-Prem TFS 2017 Update 3 RTM (15.117.27024.0)

## What's not working?
On a single machine with a few agents installed as 'runAsAutoLogon' only one agent is brought online after machine restart. To enable remaining agents you need to manually logon to machine to create a windows session (RDP works too).

**Comment by TingluoHuang** [comment] 2018-04-02 17:52
@dpksinghal for taking look at this issue related to `autologon` issue

**Comment by abhishkk** [comment] 2018-04-11 17:52
@Virenta Multiple agents can be configured with multiple users. But autologon being a machine wide setting, can be applied to a single user only. This is the reason warning is shown while configuring multiple agents.

So, the behavior of bringing online only one agent is as designed.

**Comment by abhishkk** [comment] 2018-04-12 13:41
@Virenta Sorry, but its not possible to enable autologon feature for multiple agents even if using different users/accounts.

**Comment by TingluoHuang** [comment] 2018-06-12 14:00
@Virenta i am going to close this issue, let us know if you need more help.

**Closed by TingluoHuang** 2018-06-12 14:00 UTC
