### ISSUE TITLE
The type initializer for 'System.Net.Http.CurlHandler' threw an exception.

### ISSUE THREAD

**Issue by rahulrulez** [Microsoft/vsts-agent#185] opened 2016-05-21 09:53 UTC
I am trying to setup Mac OSX on-prem agent, however getting this issue while configuration.. 

```
Apples-Mac-mini:vsts Apple$ ./config.sh

>> End User License Agreements:

Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /Users/Apple/vsts/externals/tee/license.html

Enter accept the Team Explorer Everywhere license agreement now? (Y/N) (press enter for N) > Y

>> Connect:

Enter server URL > https://{accountNameRemoved}.visualstudio.com
Enter authentication type (press enter for PAT) > PAT
Enter personal access token > ****************************************************
Connecting to server ...
The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
Failed to connect.  Try again or ctrl-c to quit
Enter server URL > 

```

**Comment by danbridgellc** [comment] 2016-05-21 19:58
Have you installed OpenSSL?

**Comment by bryanmacfarlane** [comment] 2016-05-24 17:22
Dupe of https://github.com/Microsoft/vsts-agent/issues/110

**Comment by bryanmacfarlane** [comment] 2016-05-24 17:22
See instructions for mac

**Closed by bryanmacfarlane** 2016-05-24 17:22 UTC
Labels: duplicate

**Comment by nickrandolph** [comment] 2016-07-30 22:26
This is still an issue as the instructions for mac don't work. Command to upgrade openssl doesn't force the link to override system default

**Comment by morrisonbrett** [comment] 2016-10-21 23:29
This is an issue. Target machines don't need dotnet core installed, and they shouldn't need openssl installed.

In distributing the binaries as artifacts/platformname, the idea should be that you have everything you need to run.  Because of this issue, users have to install openssl on macOS.  There shouldn't be a hard dependency.

**Comment by bryanmacfarlane** [comment] 2016-10-22 12:11
@morrisonbrett - it's not our dependency.  It's a dotnet core dependency.  The dotnet team is working right now on eliminating that dependency.  But even then, note than on linux you have to apt-get some core stuff.

**Comment by morrisonbrett** [comment] 2016-10-22 17:14
Excellent. In the mean time, I updated the install procedure of a program I wrote to instruct the users to install Openssl.  Once the dependency is removed, I'll be able to eliminate the guidance.
