### ISSUE TITLE
Nested macro malformed when loaded from variable in release definition and passing into taskgroup parameter

### ISSUE THREAD

**Issue by schnitty** [Microsoft/vsts-agent#692] opened 2016-11-23 01:16 UTC
[FailedDeployment.zip](https://github.com/Microsoft/vsts-agent/files/607946/FailedDeployment.zip)
## **Agent version and platform**
Version of your agent? 2.109.1.
<br>
OS of the machine running the agent? Windows<br>
## **VSTS type and version**
VisualStudio.com
<br>
If VisualStudio.com, what is your account name? https://pulselogistics.visualstudio.com
<br>
## **What's not working?** 
It seems like a variable that is set in the release or environment of release is not being resolved properly when passed into a variable of a task group.
I have had a working build and release for quite some time and have just refactored it to make use of the new task group feature released recently.

If I hard code the parameter value in the task group as such:

![image](https://cloud.githubusercontent.com/assets/6099451/20547582/10573ac0-b16d-11e6-86c1-f2ea22d4bb94.png)
NB: pulse.version parameter is hard coded.

The release succeeds.  The 7z Extract step at the end is able to find the file and extract it ok.

If however I set the parameter to load from a variable I have set on the release

![image](https://cloud.githubusercontent.com/assets/6099451/20547632/67cacec0-b16d-11e6-8e28-7b0e3c4e4310.png)
NB: pulse.version is set to $(pulse.version)

![image](https://cloud.githubusercontent.com/assets/6099451/20547652/8037c616-b16d-11e6-9712-d00092b5914e.png)

The 7zExtract task fails as it isn't able to find the file.  
This only seems to be the case when the variables are nested like the following:

`$(DeploymentFolder)\Pulse.Wms.RadioFrequency.$(pulse.version)-$(Release.Artifacts.Pulse.Wms.RadioFrequency.$(pulse.version).BuildId).7z`

and when it is loading from the release variables that it fails.

Log when it fails from loading the value from the variable on the release
![image](https://cloud.githubusercontent.com/assets/6099451/20547757/48a2d320-b16e-11e6-8caf-17c7cc768dd5.png)

Log when it succeeds from loading the value from the hard coded value set in the task group parameter
![image](https://cloud.githubusercontent.com/assets/6099451/20547857/dd705b12-b16e-11e6-9706-65eb975c31ea.png)

Looking through the diagnostic log seems to indicate that it is malforming the macro
[2016-11-23 00:17:29Z VERB VarUtil] Found macro candidate: 'Release.Artifacts.Pulse.Wms.RadioFrequency.$(Pulse.Version'
[2016-11-23 00:17:29Z VERB VarUtil] Get 'Release.Artifacts.Pulse.Wms.RadioFrequency.$(Pulse.Version' (not found)

vs

[2016-11-23 00:28:13Z VERB VarUtil] Found macro candidate: 'Release.Artifacts.Pulse.Wms.RadioFrequency.65h.BuildId'
[2016-11-23 00:28:13Z VERB VarUtil] Get 'Release.Artifacts.Pulse.Wms.RadioFrequency.65h.BuildId': '431'
[2016-11-23 00:28:13Z VERB VarUtil] Macro found.

**Comment by TingluoHuang** [comment] 2016-11-23 02:30
@schnitty I don't think we support Nested variable at all, but we do support recursive variable.
What's your task group definition? how did you end up with nested variable?

**Comment by schnitty** [comment] 2016-11-23 02:56
This is the task definition within a task group that I have created.
Note the area in highlighted in red.
The $(pulse.version) variable is within the bounds of another variable.
 
![nestedmacro](https://cloud.githubusercontent.com/assets/6099451/20549825/ba9a3e1c-b17f-11e6-9e06-bf921c87d47c.png)

The thing that is weird is that this works fine when I set the parameter value on the task group to a hard coded value.  If I set the parameter to value to look up a variable then it doesn't work.

So it seems that resolution of nested variables like that works ok but something is getting messed up when it has to resolve the value not from what is directly set on the parameter in the task group but from the variable set at the global release definition level.

**Comment by ericsciple** [comment] 2016-11-23 03:02
@TingluoHuang  i was confused by the nested variable claim as well. i think this may work sometimes because iirc one level expansion occurs server side.

i think the behavior differences manifest with task groups, since it expands server side.

side note, i looked at varutil.cs and it's actually coded to prevent expansion for macro within a macro (e.g. `$(hello$(world))`, but is coded to support expansion for macros within a variable value (e.g. a=`$(b)`, b=`$(c)`)

**Comment by schnitty** [comment] 2016-11-23 03:05
Sorry if I confused anyone.  What should I have called it?  macro within macro?

**Comment by ericsciple** [comment] 2016-11-23 03:10
@chrisrpatterson @bansalaseem any thoughts about the confusion of variable expansion differences with task groups?

Here are two more issues:
https://github.com/Microsoft/vsts-tasks/issues/3116
https://github.com/Microsoft/vsts-tasks/issues/2439

is there a potential solution here that involves not expanding the variable values server side?

**Comment by TingluoHuang** [comment] 2018-06-16 03:31
i am going to close this issue, the issue is not related to the agent itself.

**Closed by TingluoHuang** 2018-06-16 03:31 UTC
