### ISSUE TITLE
Nuget.exe version for Hosted Agent is too old

### ISSUE THREAD

**Issue by Javietto** [Microsoft/vsts-agent#601] opened 2016-09-20 09:47 UTC
Current agent version: '2.105.6'
VSTS type: VisualStudio.com

Restore packages step is failing because the version used by hosted agent for nuget.exe is too old.

Issue is shown here: https://github.com/Microsoft/UWPCommunityToolkit/issues/232 and a workaround is provided via powershell by downloading latest nuget.exe version and using that to restore packages.

Is this going to be fixed? When is the hosted agent being updated so it uses a recent version of nuget.exe?

Thank you

**Comment by bryanmacfarlane** [comment] 2016-09-20 10:56
Duplicate of https://github.com/Microsoft/vsts-agent/issues/582

That covers all the details.

**Comment by bryanmacfarlane** [comment] 2016-09-20 10:56
I'll forward this to packaging team though.

**Closed by bryanmacfarlane** 2016-09-20 10:56 UTC
