### ISSUE TITLE
VSTS Agents: Ant build step is getting added additional parameters for Options input

### ISSUE THREAD

**Issue by penupati** [Microsoft/vsts-agent#591] opened 2016-09-09 06:10 UTC
## **Agent version and platform**
Version of your agent? 4.2.0
<br>
OS of the machine running the agent? Linux...
<br>
## **VSTS type and version**
VisualStudio.com 
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
<br>
If VisualStudio.com, what is your account name? http://aspectenterprise.visualstudio.com
<br>
## **What's not working?** 
Ant build step is adding additional parameters at the end of Option input value.

: /ci04_home/AspectAdmin03/ci04_agent03/_work/3/s -Dunit.test=com.oilspace.apps.aspect.admin.TestAspectAdmin -logfile tests_console_output.txt/src

/src - This is getting added at the end of the statement.

Actual out put should be 
 /ci04_home/AspectAdmin03/ci04_agent03/_work/3/s -Dunit.test=com.oilspace.apps.aspect.admin.TestAspectAdmin -logfile tests_console_output.txt/

Because of this our Junit test cases are getting failed. This issue started from 07th Sep onwards.
Can you please let us know how to resolve this?

<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here. 

[2016-09-08T14:37:34.796Z] vsoagent:> initAgent<<<<<<<<<< 

2016-09-08T14:37:34.797Z: Agent Started.
2016-09-08T14:37:34.798Z: Listening for agent: AE-DT01-CI04_Lnx02
[2016-09-08T14:37:34.798Z] vsoagent:> created message listener

2016-09-08T14:37:34.798Z: starting listener...

**Comment by DavidStaheli** [comment] 2016-09-09 11:11
Thanks @penupati.  I'm closing this issue as a duplicate of [#2463](https://github.com/Microsoft/vsts-tasks/issues/2463) in the Microsoft/vsts-tasks repo.

**Closed by DavidStaheli** 2016-09-09 11:11 UTC
