### ISSUE TITLE
Linux agent removes double quotes from CmdLine build task arguments after TFS migration

### ISSUE THREAD

**Issue by spashx** [Microsoft/vsts-agent#1468] opened 2018-03-22 16:52 UTC
## Agent Version and Platform
TFS 2017 UPD3 on premise
agent version  2.122.1   
Running on Ubuntu 14.04

## VSTS Type and Version
TFS 2015 UPD1 on premise migrated to TFS 2017 UPD3 on premise

## What's not working?
After migration, all our CmdLine build steps with arguments containing double quotes, loose their double quotes when steps are executed.
This appeared after migration of our TFS2015 UPD1 instance to TFS2017 UDP3, with agent version 2.111.1 (the former one we used) or latest 2.122.1 (we tried both).

ex:

```
...
check path : /var/lib/vsoagent8/agent/_work/_tasks/CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9/1.1.3/task.json
set resource file to: /var/lib/vsoagent8/agent/_work/_tasks/CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9/1.1.3/task.json
system.culture=en-US
filename=cat
check path : /bin/cat
cat=/bin/cat
workingFolder=/var/lib/vsoagent8/agent/_work/1/s
testing directory '/var/lib/vsoagent8/agent/_work/1/s'
arguments=blabla="quoted text"                    <=======
/bin/cat arg: blabla="quoted text"
failOnStandardError=false
exec tool: /bin/cat
Arguments:
blabla=quoted text <======
/bin/cat blabla=quoted text
```

Sometime is IS necessary to have double quotes in arguments.
Ex: calling make with variables like:
`make MY_VAR="--param1 value1 --param2 value2"`

**Comment by TingluoHuang** [comment] 2018-03-22 17:00
@spashx i guess this might be a task issue. can you find a good build and compare the logs?
the header of each log should print out the task information like this:
![image](https://user-images.githubusercontent.com/1750815/37785575-e7367598-2dd0-11e8-98f9-2beff9b32522.png)

**Comment by bryanmacfarlane** [comment] 2018-03-22 23:57
create an issue in vsts-tasks
Also, have you tried escaping like you would on the command line? \\"?

**Comment by spashx** [comment] 2018-03-23 10:40
@TingluoHuang 

Here is the output with a TFS2015 UPD1 server, agent 2.111.1:
```
2018-03-23T10:16:22.2818850Z ==============================================================================
2018-03-23T10:16:22.2820540Z Task         : Command Line
2018-03-23T10:16:22.2822070Z Description  : Run a command line with arguments
2018-03-23T10:16:22.2823570Z Version      : 1.0.12
2018-03-23T10:16:22.2825020Z Author       : Microsoft Corporation
2018-03-23T10:16:22.2826500Z Help         : [More Information](http://go.microsoft.com/fwlink/?LinkID=613735)
2018-03-23T10:16:22.2828040Z ==============================================================================
2018-03-23T10:16:23.0449210Z /bin/cat failed with return code: 1
2018-03-23T10:16:23.0484010Z ##[debug]filename=cat
2018-03-23T10:16:23.0514400Z Return code: 1
2018-03-23T10:16:23.0516270Z ##[debug]check path : /bin/cat
2018-03-23T10:16:23.0517800Z ##[debug]cat=/bin/cat
2018-03-23T10:16:23.0519380Z ##[debug]arguments=a "b"
2018-03-23T10:16:23.0521000Z ##[debug]workingFolder=/var/lib/vsoagent6/agent/_work/28/s
2018-03-23T10:16:23.0522610Z ##[debug]failOnStandardError=false
2018-03-23T10:16:23.0524060Z [command]/bin/cat a "b" <=========== as expected

```

**Comment by bryanmacfarlane** [comment] 2018-03-23 10:56
Add a link here.

Note:
- 2015 version of task had bugs in handling escaping
- a \\"b\\" might be a bug but not really sensical because no need to escape quoting - escaping is for a quote inside of quotes.

Cases:
- pass a b?  just pass a b.  a "b" also works
- escape a quote pass a b"c?  pass a "b\"c"
- handle spaces pass xxx and Hello World?  xxx "Hello World"

The cases above are consistent with the shell

**Comment by spashx** [comment] 2018-03-23 14:26
> pass a b? just pass a b. a "b" also works
>escape a quote pass a b"c? pass a "b"c"
>handle spaces pass xxx and Hello World? xxx "Hello World"

Not sure to understand you clearly. Can you ellaborate a little bit ? thanks.

**Comment by TingluoHuang** [comment] 2018-06-27 03:52
Closing this one as the issue is related to command line task.

**Closed by TingluoHuang** 2018-06-27 03:52 UTC
