### ISSUE TITLE
Publish Artifact task using share option does not work correctly on Windows or Linux

### ISSUE THREAD

**Issue by bbusacker** [Microsoft/vsts-agent#501] opened 2016-08-15 18:14 UTC
## **Agent version and platform**
Version of your agent? 2.104.2<br>
Windows 10
Linux CentOS 7.1
<br>
## **VSTS type and version**
On-Prem TFS
<br>
15 RC1
<br>
## **What's not working?** 
Publish Artifact Task  now requires escaping the UNC path when it didn't used to.   Otherwise task fails to work on both Linux and Windows
On Linux, if you use escaped UNC path it does not copy the files and does not fail the task even though files weren't copied.  It does however associate the artifact even though nothing is there.
<br>

## **Build log on Windows where non-escaped UNC path causes failure**
2016-08-15T16:57:52.3560684Z ##[section]Starting: Publish Artifact: drop
2016-08-15T16:57:52.7951030Z ##[debug]agent.workFolder=E:\TfsBuildAgents\Agent2-BOWDMXTFS01\_work
2016-08-15T16:57:52.7991008Z ##[debug]loading inputs and endpoints
2016-08-15T16:57:52.8001025Z ##[debug]loading ENDPOINT_AUTH_$/
2016-08-15T16:57:52.8021183Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_$/_ACCESSTOKEN
2016-08-15T16:57:52.8021183Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2016-08-15T16:57:52.8031066Z ##[debug]loading ENDPOINT_AUTH_SCHEME_$/
2016-08-15T16:57:52.8031066Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2016-08-15T16:57:52.8031066Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2016-08-15T16:57:52.8051046Z ##[debug]loading INPUT_ARTIFACTNAME
2016-08-15T16:57:52.8051046Z ##[debug]loading INPUT_ARTIFACTTYPE
2016-08-15T16:57:52.8061013Z ##[debug]loading INPUT_PATHTOPUBLISH
2016-08-15T16:57:52.8061013Z ##[debug]loading INPUT_TARGETPATH
2016-08-15T16:57:52.8070977Z ##[debug]loaded 10
2016-08-15T16:57:52.8070977Z ##[debug]check path : E:\TfsBuildAgents\Agent2-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\task.json
2016-08-15T16:57:52.8080970Z ##[debug]set resource file to: E:\TfsBuildAgents\Agent2-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\task.json
2016-08-15T16:57:52.8080970Z ##[debug]system.culture=en-US
2016-08-15T16:57:52.8151032Z ##[debug]PathtoPublish=E:\TfsBuildAgents\Agent2-BOWDMXTFS01\_work\1\a
2016-08-15T16:57:52.8151032Z ##[debug]check path : E:\TfsBuildAgents\Agent2-BOWDMXTFS01\_work\1\a
2016-08-15T16:57:52.8160992Z ##[debug]ArtifactName=drop
2016-08-15T16:57:52.8171038Z ##[debug]ArtifactType=FilePath
2016-08-15T16:57:52.8171038Z ##[debug]TargetPath=\\bowdmxtfs01\Builds\Windows DMX-UFS CI\Windows DMX-UFS CI_4.0.160815.4
2016-08-15T16:57:52.8291008Z ##[debug]creating path: \\bowdmxtfs01\Builds\Windows DMX-UFS CI\Windows DMX-UFS CI_4.0.160815.4\drop
2016-08-15T16:57:57.2374429Z shell.js: internal error
2016-08-15T16:57:57.2384437Z RangeError: Maximum call stack size exceeded
2016-08-15T16:57:57.2384437Z     at String.slice (native)
2016-08-15T16:57:57.2384437Z     at Object.dirname (path.js:795:17)
2016-08-15T16:57:57.2384437Z     at mkdirSyncRecursive (E:\TfsBuildAgents\Agent2-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\node_modules\shelljs\src\mkdir.js:7:22)
2016-08-15T16:57:57.2384437Z     at mkdirSyncRecursive (E:\TfsBuildAgents\Agent2-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\node_modules\shelljs\src\mkdir.js:16:3)
2016-08-15T16:57:57.2384437Z     at mkdirSyncRecursive (E:\TfsBuildAgents\Agent2-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\node_modules\shelljs\src\mkdir.js:16:3)
2016-08-15T16:57:57.2384437Z     at mkdirSyncRecursive (E:\TfsBuildAgents\Agent2-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\node_modules\shelljs\src\mkdir.js:16:3)
2016-08-15T16:57:57.2384437Z     at mkdirSyncRecursive (E:\TfsBuildAgents\Agent2-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\node_modules\shelljs\src\mkdir.js:16:3)
2016-08-15T16:57:57.2384437Z     at mkdirSyncRecursive (E:\TfsBuildAgents\Agent2-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\node_modules\shelljs\src\mkdir.js:16:3)
2016-08-15T16:57:57.2384437Z     at mkdirSyncRecursive (E:\TfsBuildAgents\Agent2-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\node_modules\shelljs\src\mkdir.js:16:3)
2016-08-15T16:57:57.2384437Z     at mkdirSyncRecursive (E:\TfsBuildAgents\Agent2-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\node_modules\shelljs\src\mkdir.js:16:3)
2016-08-15T16:57:57.5664681Z ##[error]Exit code 1 returned from process: file name 'E:\TfsBuildAgents\Agent2-BOWDMXTFS01\externals\node\bin\node.exe', arguments '"E:\TfsBuildAgents\Agent2-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\publishbuildartifacts.js"'.
2016-08-15T16:57:57.5704716Z ##[debug]Microsoft.VisualStudio.Services.Agent.ProcessExitCodeException: Exit code 1 returned from process: file name 'E:\TfsBuildAgents\Agent2-BOWDMXTFS01\externals\node\bin\node.exe', arguments '"E:\TfsBuildAgents\Agent2-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\publishbuildartifacts.js"'.
   at Microsoft.VisualStudio.Services.Agent.ProcessInvoker.<ExecuteAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunAsync>d__0.MoveNext()
2016-08-15T16:57:57.5704716Z ##[section]Finishing: Publish Artifact: drop

## **Worker's diag log on Linux where files are not getting copied**
[2016-08-15 17:55:07Z INFO StepsRunner] Processing step: DisplayName='Publish Artifact: drop', AlwaysRun=True, ContinueOnError=True, Critical=False, Enabled=True, Finally=False
[2016-08-15 17:55:07Z INFO StepsRunner] Starting the step.
[2016-08-15 17:55:07Z INFO TaskManager] Loading task definition '/home/ufs/TfsBuildAgents/Agent1-DMX-UFS1/_work/_tasks/PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe/1.0.34/task.json'.
[2016-08-15 17:55:07Z INFO TaskRunner] The original input is a rooted path, return absolute path: /home/ufs/TfsBuildAgents/Agent1-DMX-UFS1/_work/1/a
[2016-08-15 17:55:07Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.IJobExtension'
[2016-08-15 17:55:07Z INFO BuildJobExtension] Build JobExtension resolving path use source provide: 
[2016-08-15 17:55:07Z INFO BuildJobExtension] The Default Path Root of Build JobExtension is build.sourcesDirectory: /home/ufs/TfsBuildAgents/Agent1-DMX-UFS1/_work/1/s
[2016-08-15 17:55:07Z INFO BuildJobExtension] After prefix Default Path Root provide by JobExtension: /home/ufs/TfsBuildAgents/Agent1-DMX-UFS1/_work/1/s
[2016-08-15 17:55:07Z INFO BuildJobExtension] Return absolute path after prefix DefaultPathRoot: /home/ufs/TfsBuildAgents/Agent1-DMX-UFS1/_work/1/s
[2016-08-15 17:55:07Z INFO TaskRunner] build JobExtension resolved a rooted path:: /home/ufs/TfsBuildAgents/Agent1-DMX-UFS1/_work/1/s
[2016-08-15 17:55:07Z INFO ProcessInvoker] Starting process:
[2016-08-15 17:55:07Z INFO ProcessInvoker]   File name: '/home/ufs/TfsBuildAgents/Agent1-DMX-UFS1/externals/node/bin/node'
[2016-08-15 17:55:07Z INFO ProcessInvoker]   Arguments: '"/home/ufs/TfsBuildAgents/Agent1-DMX-UFS1/_work/_tasks/PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe/1.0.34/publishbuildartifacts.js"'
[2016-08-15 17:55:07Z INFO ProcessInvoker]   Working directory: '/home/ufs/TfsBuildAgents/Agent1-DMX-UFS1/_work/1/s'
[2016-08-15 17:55:07Z INFO ProcessInvoker]   Require exit code zero: 'True'
[2016-08-15 17:55:07Z INFO ProcessInvoker]   Encoding web name:  ; code page: ''
[2016-08-15 17:55:07Z INFO ProcessInvoker] Process started with process id 29976, waiting for process exit.
[2016-08-15 17:55:07Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2016-08-15 17:55:07Z INFO JobServerQueue] Try to upload 1 log files or attachments, success rate: 1/1.
[2016-08-15 17:55:08Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:01.4577354.
[2016-08-15 17:55:08Z INFO AsyncCommandContext] Start flush buffered output.
[2016-08-15 17:55:08Z INFO AsyncCommandContext] Finsh flush buffered output.
[2016-08-15 17:55:08Z INFO AsyncCommandContext] Wait till async command task to finish.
[2016-08-15 17:55:08Z INFO StepsRunner] Step result: 
[2016-08-15 17:55:08Z INFO StepsRunner] Current state: job state = '', step failed = False, critical step failed = False

**Comment by bbusacker** [comment] 2016-08-16 19:57
It turns out using \\\\server\\folder is not a workaround.   If that syntax is used it create a folder on the build machine at \server\folder where server is not a network share but a non-shared folder on the build server with the same name as the networks server.  Below is the output if  \\server\folder syntax is used instead.

******************************************************************************
Starting: Publish Artifact: drop
******************************************************************************
agent.workFolder=E:\TfsBuildAgents\Agent1-BOWDMXTFS01\_work
loading inputs and endpoints
loading ENDPOINT_AUTH_$/
loading ENDPOINT_AUTH_PARAMETER_$/_ACCESSTOKEN
loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
loading ENDPOINT_AUTH_SCHEME_$/
loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
loading INPUT_ARTIFACTNAME
loading INPUT_ARTIFACTTYPE
loading INPUT_PATHTOPUBLISH
loading INPUT_TARGETPATH
loaded 10
check path : E:\TfsBuildAgents\Agent1-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\task.json
set resource file to: E:\TfsBuildAgents\Agent1-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\task.json
system.culture=en-US
PathtoPublish=E:\TfsBuildAgents\Agent1-BOWDMXTFS01\_work\2\a
check path : E:\TfsBuildAgents\Agent1-BOWDMXTFS01\_work\2\a
ArtifactName=drop
ArtifactType=FilePath
TargetPath=\\bowdmxtfs01.micron.com\builds\Windows DMX-eMMC CI\Windows DMX-eMMC CI_4.1.160816.4
creating path: \\bowdmxtfs01.micron.com\builds\Windows DMX-eMMC CI\Windows DMX-eMMC CI_4.1.160816.4\drop
shell.js: internal error
RangeError: Maximum call stack size exceeded
    at String.slice (native)
    at Object.dirname (path.js:795:17)
    at mkdirSyncRecursive (E:\TfsBuildAgents\Agent1-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\node_modules\shelljs\src\mkdir.js:7:22)
    at mkdirSyncRecursive (E:\TfsBuildAgents\Agent1-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\node_modules\shelljs\src\mkdir.js:16:3)
    at mkdirSyncRecursive (E:\TfsBuildAgents\Agent1-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\node_modules\shelljs\src\mkdir.js:16:3)
    at mkdirSyncRecursive (E:\TfsBuildAgents\Agent1-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\node_modules\shelljs\src\mkdir.js:16:3)
    at mkdirSyncRecursive (E:\TfsBuildAgents\Agent1-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\node_modules\shelljs\src\mkdir.js:16:3)
    at mkdirSyncRecursive (E:\TfsBuildAgents\Agent1-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\node_modules\shelljs\src\mkdir.js:16:3)
    at mkdirSyncRecursive (E:\TfsBuildAgents\Agent1-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\node_modules\shelljs\src\mkdir.js:16:3)
    at mkdirSyncRecursive (E:\TfsBuildAgents\Agent1-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\node_modules\shelljs\src\mkdir.js:16:3)
Exit code 1 returned from process: file name 'E:\TfsBuildAgents\Agent1-BOWDMXTFS01\externals\node\bin\node.exe', arguments '"E:\TfsBuildAgents\Agent1-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\publishbuildartifacts.js"'.
Microsoft.VisualStudio.Services.Agent.ProcessExitCodeException: Exit code 1 returned from process: file name 'E:\TfsBuildAgents\Agent1-BOWDMXTFS01\externals\node\bin\node.exe', arguments '"E:\TfsBuildAgents\Agent1-BOWDMXTFS01\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.34\publishbuildartifacts.js"'.

**Comment by bbusacker** [comment] 2016-08-16 21:50
Copy Files task also has exact same defect.  It does not allow the use of a UNC path for the destination directory even though documentation for that field says that it does.

**Comment by ericsciple** [comment] 2016-08-17 15:02
Thanks! I believe the problem is the share does not exist or the process does not have access to see it. I have an [outstanding PR](https://github.com/Microsoft/vsts-task-lib/pull/115) to improve the error messages returned from `mkdirP`.

I was not previously aware, but it appears that three or more leading slashes causes nodejs to treat the path as a local rooted path (from root of drive wherever cwd is). I just confirmed by playing around with fs.statSync from an interactive node session.

**Comment by ericsciple** [comment] 2016-08-17 15:14
Regarding the issue you are seeing on Linux, it is probably creating a folder `\\server\path` locally somewhere under the agent directory or work directory. I know that if you don't use UNC format associating the artifact fails on Linux.

I have [a PR](https://github.com/Microsoft/vsts-tasks/pull/2282) where I'm trying to figure out the correct behavior on Linux - I think skip artifact creation is the correct thing and probably a warning in the build log. Artifact creation has special meaning (used for cleanup jobs, displayed in UI with copy-to-clipboard hyperlink). I'm not sure yet what the correct experience is for the Publish Artifacts task on OSX/Linux. My goal with the PR is a short-term fix.

I'm going to go ahead and close this issue. Feel free to reopen it if I'm wrong about the cause of the issue you are hitting on Windows. There is an [issue in the tasks repo](https://github.com/Microsoft/vsts-tasks/issues/2261) tracking this already. I don't believe it is an agent issue (please re-open if I'm wrong).

The task issue on Linux is [tracked here](https://github.com/Microsoft/vsts-tasks/issues/2049). Again please re-open if I'm wrong and it is agent related.

**Closed by ericsciple** 2016-08-17 15:14 UTC

**Comment by bbusacker** [comment] 2016-08-17 15:19
Hi Eric,  The share does exist. It is physically on the same server as the build agent.   It  also worked with the old agent.


As seen in my issue,  copy files also doesn’t work and copy files doesn’t work with either a unc or an absolute path.

Brandon

**Comment by ericsciple** [comment] 2016-08-17 15:58
Are you running the new agent as a different service account? Or with different elevated-ness? If you log in as the account, enter a node session in a console, and type `require('fs').statSync('\\\\server\\share')` you should be able to repro and troubleshoot.

**Comment by bbusacker** [comment] 2016-08-17 16:21
Hi Eric,

I stand corrected.  Things are working fine now.   The issue was I was running the agent service and NETWORK SERVICE which is the default and NETWORK SERVICE didn’t have permission to my file system or share.  I’m now running it as my generic build account user and that has made all the difference.  Thanks for getting me set straight.

I’ll close this issue now.

I would like some clarification as to why you default the server user to network service.   I think that is a bad idea.   I think it is the origin of many bizarre unexpected issues.  I assume network service will have more permissions than it actually does.

Can you provide some guidance on when you would use network service?  Do you need to treat network or local service as just another user?  So do you need to add network service to your file system and share permissions?  I also couldn’t use my test adapters so those needed to be installed as network service as well.  Just some clarification would help.  Thanks.

Brandon

**Comment by ericsciple** [comment] 2016-08-17 17:33
The config prompts which service account to use, and as a convenience we provide a default value so you can hit enter to accept the default. I see a couple options here:
1) Don't default at all. That would force users to type `NT AUTHORITY\NETWORK SERVICE` if they indeed want to use network service - not a good experience.
2) Default to the current user. I don't think that is a good option as it leads the customer down an insecure path. Local admin is required to install a Windows service, so it would be better for customers to enter a different service account (and grant only required permissions) when running the Windows service.

Network service is just another user. It's identified in AD as `<COMPUTER_NAME>$`. E.g. if your computer name is `JOHN_COMPUTER`, then you would grant permissions within your network to `JOHN_COMPUTER$`.

Whether to use network service or a service account ultimately comes down the preference of the administrator and the scenario that you're trying to acheive. Network service is easier to setup and does not require managing credentials for the service account. Using a service account offers more granular permission management, and can simply disable a service account to disable permissions. I personally feel like service account is the cleaner approach, but both have advantages.

**Comment by bbusacker** [comment] 2016-08-17 17:42
Thanks for the explanation.  It seems strange that if you are running your agent on JOECOMPUTER that the network service account permissions for that computer is not just automatically in place but it appears that is not the case.
