### ISSUE TITLE
SYSTEM_TEAMFOUNDATIONCOLLECTIONURI is wrongly set

### ISSUE THREAD

**Issue by nigurr** [Microsoft/vsts-agent#381] opened 2016-07-11 11:40 UTC
1. Latest build agent built from the source
2. Configure Agent to local tfs `http://localhost:8080/tfs/`
3. print the `SYSTEM_TEAMFOUNDATIONCOLLECTIONURI` property
**http://localhost:8080/tfs/20160710_182550/**

1. Latest build agent built from the source
2. Configure Agent to local tfs `http://dtaetoe:8080/tfs/`
3. print the `SYSTEM_TEAMFOUNDATIONCOLLECTIONURI` property
**http://dtaetoe:8080/tfs/20160710_182550/**

1. Existing Windows Agent
2. Configure Agent to local tfs `http://localhost:8080/tfs/`
3. print the `SYSTEM_TEAMFOUNDATIONCOLLECTIONURI` property 
**http://dtaetoe:8080/tfs/20160710_182550/**

Both of the agents are configured to `latest local tfs`

![image](https://cloud.githubusercontent.com/assets/15208679/16729470/4732654e-478a-11e6-9445-7f316fcd11bb.png)

Expected to print TFS url, not based on the how agent is configured

**Comment by ericsciple** [comment] 2016-07-11 14:49
Closing as by design. This is a feature that was added in the new agent to enable scenarios related to proxy configuration. The agent should connect based on the URL it was configured with.

**Comment by bryanmacfarlane** [comment] 2016-07-11 15:08
Yes.  the big issue was non-domain joined Linux, OSX machines and even non trusted windows domain.  In those scenarios it's typical for the agent to know the server by a different name than is in the notification url.  There's even some scenarios where mac knows it by machinename.local and windows accesses by machinename.  So, the agent talks to the server by what it knows the server by.  The agent owns how it chooses to resolve the machinename.  How you configure the server url in the agent is how it will access the server (how it should be).  Server controls the paths to the resources (relative urls)

**Comment by nigurr** [comment] 2016-07-12 04:18
@bryanmacfarlane i do accept the facts here, it breaks compat with old agent to new agent. Any task [DTA] depends on TFS URL for configuring certain things do fail. We do pass this URL to configure Test Agent against TFS, now once we pass to Test Agent machine, it tries to resolve `http://localhost:8080/tfs/` which is completely wrong.

**Comment by bryanmacfarlane** [comment] 2016-07-12 04:36
No. It doesn't break compat.  The host name you configure with is the host name it will use to connect to the server

The agent/client owns how it connects and resolved the server.  

Your test agent us free to resolve via that URL or the notification URL, your choice

**Closed by bryanmacfarlane** 2016-07-12 04:36 UTC
Labels: bug

**Comment by bryanmacfarlane** [comment] 2016-07-12 04:44
If you want multiple agents to resolve the server, local host is a non sensical choice

**Comment by nigurr** [comment] 2016-07-12 06:50
I have opened discussion via email as I need more info regarding the same.
