### ISSUE TITLE
When using collection url while configuring the agent against on-prem TFS the failure message is not helpful.

### ISSUE THREAD

**Issue by sachinma** [Microsoft/vsts-agent#481] opened 2016-08-04 11:39 UTC
## **Agent version and platform**
Version of your agent? 2.104.1
<br>
OS of the machine running the agent? Windows
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS? On-Prem
<br>
If On-Prem TFS, which release? Latest internal
<br>
If VisualStudio.com, what is your account name? NA
<br>
## **What's not working?** 
The error message is not helpful. Current message is: TF14045: The identity could not be found.
<br>A more helpful message telling that it shouldn't be a collection URL would be better
[Agent_20160804-052752-utc.log.txt](https://github.com/Microsoft/vsts-agent/files/401508/Agent_20160804-052752-utc.log.txt)
<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here.

**Comment by bryanmacfarlane** [comment] 2016-08-04 11:46
Dupe of https://github.com/Microsoft/vsts-agent/issues/468

Just fixed

**Comment by sachinma** [comment] 2016-08-04 12:21
This is slightly different from the resolved issue where access to hidden file is fixed.

I see that the current understanding is that user should be configuring with correct URL as per docs. However, in the current experience, if user gives collection URL, the tools shows a step "connecting to sever" which is successful. Even the agent is added successful. And it fails in the very end with an obscure message. It doesn't feel like a very good experience

**Comment by TingluoHuang** [comment] 2016-08-12 03:02
#492 will improve this. since it will take reference at what server think the agent's correct connection url.

**Closed by TingluoHuang** 2016-08-12 03:02 UTC
