### ISSUE TITLE
Agent lost communication with the server

### ISSUE THREAD

**Issue by yorhpokie** [Microsoft/vsts-agent#1495] opened 2018-04-05 01:21 UTC
## Have you tried trouble shooting?
Yes

## Agent Version and Platform
2.117.2

OS of the machine running the agent?
Windows10 and Windows Server 2012 R2

## VSTS Type and Version
On-Prem TFS 2017 Update 3

## What's not working?
We get periodic "The agent xx lost communication with the server. Verify the machine is running and has a healthy network connection." error.  About 2 to 5 times every day, on different agents.  This invalidates our pipeline run and we'd have to start over.  We've increased VSTS_HTTP_RETRY to 20 and VSTS_HTTP_TIMEOUT to 240, but we're still seeing the error.

## Agent and Worker's Diagnostic Logs
From Agent_20180320-200117-utc.log file:
[Agent_20180320-200117-utc.log](https://github.com/Microsoft/vsts-agent/files/1878296/Agent_20180320-200117-utc.log)

[2018-04-04 23:24:52Z INFO JobDispatcher] Successfully renew job request 170206, job is valid till 4/4/2018 11:29:52 PM
[2018-04-04 23:29:36Z ERR  MessageListener] Catch exception during get next message.
[2018-04-04 23:29:52Z INFO JobDispatcher] Successfully renew job request 170206, job is valid till 4/4/2018 11:34:48 PM
[2018-04-04 23:30:15Z ERR  MessageListener] System.TimeoutException: The HTTP request timed out after 00:01:40. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.<GetNextMessageAsync>d__13.MoveNext()
[2018-04-04 23:30:15Z INFO MessageListener] Retriable exception: The HTTP request timed out after 00:01:40.
[2018-04-04 23:30:15Z ERR  Terminal] WRITE ERROR: 2018-04-04 23:30:15Z: Agent connect error: The HTTP request timed out after 00:01:40.. Retrying every 15 seconds until reconnected.
[2018-04-04 23:30:15Z INFO MessageListener] Sleeping for 15 seconds before retrying.
[2018-04-04 23:31:31Z INFO JobDispatcher] Successfully renew job request 170206, job is valid till 4/4/2018 11:36:22 PM
[2018-04-04 23:31:32Z INFO Terminal] WRITE LINE: 2018-04-04 23:31:32Z: Agent reconnected.
[2018-04-04 23:32:33Z INFO JobDispatcher] Successfully renew job request 170206, job is valid till 4/4/2018 11:37:32 PM
[2018-04-04 23:36:16Z ERR  MessageListener] Catch exception during get next message.
[2018-04-04 23:37:58Z ERR  JobDispatcher] Catch exception during renew agent jobrequest 170206.
[2018-04-04 23:38:43Z ERR  JobDispatcher] System.TimeoutException: The HTTP request timed out after 00:01:40. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.JobDispatcher.<RenewJobRequestAsync>d__12.MoveNext()
[2018-04-04 23:38:43Z INFO JobDispatcher] Lock renewal has run out of retry, stop renew lock for jobrequest 170206.
[2018-04-04 23:38:43Z ERR  MessageListener] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.StreamToStreamCopy.<CopyAsyncAnyStreamToAnyStreamCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.<GetNextMessageAsync>d__13.MoveNext()
[2018-04-04 23:38:43Z INFO JobDispatcher] Send job cancellation message to worker for job 0e204464-6aff-40cb-83ee-c18f36c4d2ac.
[2018-04-04 23:38:43Z INFO MessageListener] Retriable exception: A task was canceled.
[2018-04-04 23:38:43Z ERR  Terminal] WRITE ERROR: 2018-04-04 23:38:43Z: Agent connect error: A task was canceled.. Retrying every 15 seconds until reconnected.
[2018-04-04 23:38:43Z INFO MessageListener] Sleeping for 15 seconds before retrying.
[2018-04-04 23:38:59Z INFO MessageListener] No message retrieved from session '1610e50a-6967-446e-b376-d30962760526' within last 30 minutes.
[2018-04-04 23:39:47Z INFO ProcessInvoker] Scean all processes to find relationship between all processes.
[2018-04-04 23:39:48Z INFO ProcessInvoker] Find all child processes of process '16824'.
[2018-04-04 23:39:48Z INFO ProcessInvoker] Kill process '16824'.
[2018-04-04 23:39:48Z ERR  ProcessInvoker] Ignore ArgumentException during Process.GetProcessById().
[2018-04-04 23:39:48Z ERR  ProcessInvoker] System.ArgumentException: Process with an Id of 16824 is not running.
   at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvoker.WindowsKillProcessTree()
[2018-04-04 23:39:48Z INFO ProcessInvoker] Finished process with exit code -532462766, and elapsed time 00:35:00.8932736.
[2018-04-04 23:39:48Z INFO JobDispatcher] finish job request for job 0e204464-6aff-40cb-83ee-c18f36c4d2ac with result: Abandoned
[2018-04-04 23:39:48Z INFO Terminal] WRITE LINE: 2018-04-04 23:39:48Z: Job Build completed with result: Abandoned
[2018-04-04 23:39:48Z INFO JobDispatcher] Stop renew job request for job 0e204464-6aff-40cb-83ee-c18f36c4d2ac.
[2018-04-04 23:39:48Z INFO JobNotification] Entering JobCompleted Notification
[2018-04-04 23:39:53Z INFO Terminal] WRITE LINE: 2018-04-04 23:39:53Z: Agent reconnected.

**Comment by TingluoHuang** [comment] 2018-04-05 02:11
@yorhpokie few things i would suggest:
1. you are on a pretty old version `2.117.2`, try the latest version agent `2.131.0`.
2. you need to restart the agent process in order to make those environment take affect.
3. check with your IT department, make sure the network between your build machine and tfs server is reliable, the first network error happened at `2018-03-25 23:59:58Z UTC`, see whether there is any change in your network.

**Comment by yorhpokie** [comment] 2018-04-05 18:13
@TingluoHuang Thank you for the suggestion.
When I run "Update All Agents", the agents only update to 2.122.1, not 2.131.0.  Do you know why?  Do we have to update to 2.131.0 manually?

I will check with my IT department.  However, we run 8 agents per VM, and we have 20+ VMs, but only a few agents show this error randomly.  The other agents seem to connect to the TFS server fine.

**Comment by yorhpokie** [comment] 2018-04-10 17:42
@TingluoHuang we're still seeing this issue after upgrading the agents to 2.131.0.  I have attached a new log file for you.  This is causing our submit builds to fail and thus preventing new code from going into the master branch.  We did not experience this issue in our old XAML builds.  Please make this a high priority.
[Agent_20180407-005254-utc.log](https://github.com/Microsoft/vsts-agent/files/1895727/Agent_20180407-005254-utc.log)

**Comment by japj** [comment] 2018-04-17 17:29
Hello, just to add to this. We have had similar “connection” issues in the past, which for us were in the end mostly that the agent could not get enough resources due to the load generated by the build. Perhaps that is also occurring for you?

If I may suggest to check some things: 
Check if your network issues always happen when other builds are running on the same build server/vm host?
Is there anything in your build (scripts) that might “explode” cpu load?

We had a case of spawning multiple msbuild instances concurrently with each having /m too, inside a single build and those were fighting each other and the agent for cpu. Having multiple builds running on the same server at the same time increased the frequency of occurrence. 
Once we solved this, we have only seen (obvious) network issues on (IT confirmed) network downtime. No other reasons so far. And our builds are actually a fair bit faster too.

**Comment by bryanmacfarlane** [comment] 2018-05-03 00:54
Closing based on @TingluoHuang reference above of VM running out of resources.  The point of the losing a connection message is to inform that the agent machine has gone away for some reason so the behavior is correct.  Let us know if you capture more inof on why the machine became unresponsive.

**Closed by bryanmacfarlane** 2018-05-03 00:54 UTC

**Comment by cangetright** [comment] 2021-06-04 07:30
Please
