### ISSUE TITLE
Private build agent is not able to recognize the VS2017  

### ISSUE THREAD

**Issue by girishgouda** [Microsoft/vsts-agent#1010] opened 2017-06-13 02:02 UTC
When i use a private build agent to queue the build , i get the following error

No agent could be found with the following capabilities: msbuild, visualstudio, vstest

I have installed vs2017 on the build agent and its not able to recognize the capabilities . when i see the capabilities section of build agent. I do not see the msbuild visualstudio and vstest.

I am using the latest build agent vsts-agent-win7-x64-2.117.1

We are stuck with this issue and not able to proceed further

**Comment by TingluoHuang** [comment] 2017-06-13 02:04
@girishgouda can you share your agent diag log with us? the log is under `_diag` folder in agent root directory.

**Comment by girishgouda** [comment] 2017-06-13 02:14
Hi 
Here is the log file
[logfile.docx](https://github.com/Microsoft/vsts-agent/files/1070100/logfile.docx

More information on the issue 

Earlier i was getting where the build agent was not able to reconize vs2017(15) and instead using 14 to build. Because of this some, we were not able to build the solution. I uninstalled vs2017 and vs2015 and installed vs2017 and now i see this error because it not able find vs2017 and vs2015 is removed. Hope this will help

**Comment by TingluoHuang** [comment] 2017-06-13 02:31
@girishgouda how did you installed VS2017? using the offical installer? which set of components did you select to install?
can you run the following command and share the result?
1. `E:\BootCampAgent\bin\powershell\CapabilityHelpers\..\..\..\externals\vswhere\vswhere.exe -version '[15.0,15.1)' -latest -format json`
2. `E:\BootCampAgent\bin\powershell\CapabilityHelpers\..\..\..\externals\vswhere\vswhere.exe -version [15.0,16.0) -products Microsoft.VisualStudio.Product.BuildTools -latest -format json`

**Comment by girishgouda** [comment] 2017-06-13 02:39
Yes using the offical installer. I had installed ASP.NET and web development  and azure development
I do not see Vswhere.exe in the path 
![capabilityhelper](https://user-images.githubusercontent.com/9015874/27063472-a198f2a8-500f-11e7-9cb2-18257a5ca205.png)

**Comment by TingluoHuang** [comment] 2017-06-13 03:02
@girishgouda sorry, it's a relative path. `E:\BootCampAgent\bin\powershell\CapabilityHelpers\..\..\..\externals\vswhere\vswhere.exe` should be `E:\BootCampAgent\externals\vswhere\vswhere.exe`

**Comment by girishgouda** [comment] 2017-06-13 03:08
Here the results
![comands](https://user-images.githubusercontent.com/9015874/27064164-a3357d76-5013-11e7-9f55-aac97f27ca03.png)

**Comment by girishgouda** [comment] 2017-06-13 03:10
i corrected the other command with the quote and heres the result. Both of them are returining empty or null
![commandnew](https://user-images.githubusercontent.com/9015874/27064216-e071246a-5013-11e7-859e-410179e37245.png)

**Comment by TingluoHuang** [comment] 2017-06-13 03:11
@girishgouda what about `.\vswhere.exe -all`

**Comment by girishgouda** [comment] 2017-06-13 03:15
![all](https://user-images.githubusercontent.com/9015874/27064353-908d0e90-5014-11e7-9a1d-ae58201a778d.png)

Im my localdat folder i see this 

![localdatapath](https://user-images.githubusercontent.com/9015874/27064363-994c3948-5014-11e7-8b02-77ba6bb73272.png)

**Comment by girishgouda** [comment] 2017-06-13 03:22
Earlier i had also installed the latest preview version of VS2017. So there were two version side be side . vs2017 and vs2017 preview and then i unistalled vs2017 and installed it back.Does it help

**Comment by TingluoHuang** [comment] 2017-06-13 03:27
@girishgouda thanks for the information.
@ericsciple FYI,
i think the problem is VS changed their version format that we didn't participate.
can you check whether the following path exist `c:\program file (x86)\microsoft visual studio\2017\enterprise\MSBuild\15.0\Bin\msbuild.exe`
if so, to unblock you make the following change into `"E:\BootCampAgent\bin\powershell\CapabilityHelpers\VisualStudioFunctions.ps1"`
```
line 16:
& $PSScriptRoot\..\..\..\externals\vswhere\vswhere.exe -version '[15.0,15.1)' -latest -format json 2>&1 |
change '[15.0,15.1)' -> '[15.0,16.0)'
```

**Comment by girishgouda** [comment] 2017-06-13 03:34
After chaging i still see the error 
No agent could be found with the following capabilities: msbuild, visualstudio, vstest
Do we need to remove and configure the agent

**Comment by TingluoHuang** [comment] 2017-06-13 03:36
@girishgouda did you stop and restart your agent after change the ps1 script, if you already restart the agent but still see the error, send me diag log again.

**Comment by girishgouda** [comment] 2017-06-13 03:37
how do we stop and start the agent,. I ahvent done that

**Comment by TingluoHuang** [comment] 2017-06-13 03:39
@girishgouda how did you run your agent interactive or service? if interactive, just Ctrl-C the command prompt and re-run ./run.cmd, if service, go to task manager, restart the windows service for your agent.

**Comment by girishgouda** [comment] 2017-06-13 04:55
now i am able to the star the build but the build is failing for
##[warning]Visual Studio version '15.0' not found.

**Comment by TingluoHuang** [comment] 2017-06-13 04:59
@girishgouda yeah, you also need hack the task script to unblock yourself. search all `MSBuildHelpers/PathFunctions.ps1` under your agent's `_work/_tasks` folder.
make similar change to line 189:
```
Invoke-VstsTool -FileName "$PSScriptRoot\vswhere.exe" -Arguments "-version [15.0,15.1) -latest -format json" -RequireExitCodeZero 2>&1 |
```

**Comment by girishgouda** [comment] 2017-06-13 05:15
No builing failing for test 

2017-06-13T05:10:28.2348153Z !**\obj\**
2017-06-13T05:10:28.2348153Z Test assembly filter : **\release\*unittest*.dll,!**\obj\**
2017-06-13T05:10:28.2368181Z VisualStudio version selected for test execution : latest
2017-06-13T05:10:28.2418161Z [command]powershell -NonInteractive -ExecutionPolicy Unrestricted -file E:\BootCampAgent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.0.51\vs15Helper.ps1
2017-06-13T05:10:30.0190352Z <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
2017-06-13T05:10:30.0190352Z   <Nil />
2017-06-13T05:10:30.0190352Z </Objs>
2017-06-13T05:10:30.0290342Z [command]wmic datafile where "name='C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe'" get Version /Value
2017-06-13T05:10:31.1825645Z No Instance(s) Available.
2017-06-13T05:10:31.1825645Z

**Comment by girishgouda** [comment] 2017-06-13 05:21
I changed the version of test task from latest to vs2017 then i am getting this error 

Visual Studio 2017 is not found. Try again with a version that exists on your build agent machine.

**Comment by ericsciple** [comment] 2017-06-13 10:01
a workaround would be specify the location to vstest

**Comment by ericsciple** [comment] 2017-06-13 10:32
fyi - PRs https://github.com/Microsoft/vsts-agent/pull/1014 and https://github.com/Microsoft/vsts-tasks/pull/4525

**Comment by ericsciple** [comment] 2017-06-13 10:37
@nigurr fyi - although it looks like you already merged a fix to master last week https://github.com/Microsoft/vsts-tasks/pull/4488

**Comment by TingluoHuang** [comment] 2017-07-06 04:09
both agent fix and task fix should been rolls out to all accounts, i am going to close the issue.

**Closed by TingluoHuang** 2017-07-06 04:09 UTC
