### ISSUE TITLE
Cannot connect VSTS agent from Windows Docker container: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The parameter is incorrect

### ISSUE THREAD

**Issue by alparamonov** [Microsoft/vsts-agent#770] opened 2017-01-26 15:44 UTC
## **Agent version and platform**
Version of agent: v2.111.1/vsts-agent-win7-x64-2.111.1
<br>
OS of the machine running the agent:
microsoft/windowsservercore:latest

Docker for Windows version:
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Host OS: Windows Server 2016 with Containers (10.0.14393)
VM runs in Azure. Also tested on-premises.
<br>
## **VSTS type and version**
VisualStudio.com
https://alexlexproj.visualstudio.com
<br>
## **What's not working?** 
By configuring the VSTS agent using config.cmd script inside a docker container I constantly get the following error message:
```
>> Connect:

Connecting to server ...
An error occurred while sending the request.
```
This happens in both cases: when I connect to the running container and execute the script interactively as well as from unattended mode (`config.cmd --unattended --url https://alexlexproj.visualstudio.com --agent agent1 --pool Default --auth PAT --token XXXXXXXXXXXXXXXXXXX`)

The same command works perfect from the host where the container runs.

Predicting questions about network configuration: the docker host runs in Azure and containers are able to communicate with the Internet. I download agent zip archive directly from https://github.com/Microsoft/vsts-agent/releases/download/v2.111.1/vsts-agent-win7-x64-2.111.1.zip by running `Invoke-WebRequest` inside the container.

I've also tested it from container based on `microsoft/windowsservercore` with installed Visual Studio 2015 and Build Tools. The result is always the same.

## **Agent diag log**
```
[2017-01-26 15:25:29Z INFO AgentProcess] Agent is built for Windows - win7-x64.
[2017-01-26 15:25:29Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 10.0.14393 .
[2017-01-26 15:25:29Z INFO AgentProcess] Version: 2.111.1
[2017-01-26 15:25:29Z INFO AgentProcess] Commit: f2b339f02e4065d8500c918d883f50c347b7ba57
[2017-01-26 15:25:29Z INFO AgentProcess] Culture: en-US
[2017-01-26 15:25:29Z INFO AgentProcess] UI Culture: en-US
[2017-01-26 15:25:29Z INFO HostContext] Well known directory 'Bin': 'C:\build\agent\bin'
[2017-01-26 15:25:29Z INFO HostContext] Well known directory 'Root': 'C:\build\agent'
[2017-01-26 15:25:29Z INFO AgentProcess] Validating directory permissions for: 'C:\build\agent'
[2017-01-26 15:25:29Z INFO PowerShellExeUtil] Generation: '1'
[2017-01-26 15:25:29Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1', value name 'Install': '1'
[2017-01-26 15:25:29Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\PowerShellEngine', value name 'PowerShellVersion': '2.0'
[2017-01-26 15:25:29Z INFO PowerShellExeUtil] Unsupported version. Skipping.
[2017-01-26 15:25:29Z INFO PowerShellExeUtil] Generation: '3'
[2017-01-26 15:25:29Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3', value name 'Install': '1'
[2017-01-26 15:25:29Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'PowerShellVersion': '5.1.14393.0'
[2017-01-26 15:25:29Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'ApplicationBase': 'C:\Windows\System32\WindowsPowerShell\v1.0'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework', value name 'InstallRoot': 'C:\Windows\Microsoft.NET\Framework64\'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP' contains sub keys:
[2017-01-26 15:25:29Z INFO NetFrameworkUtil]  'CDF'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil]  'v3.0'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil]  'v4'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil]  'v4.0'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name 'Version' is null.
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name '' is null.
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0' contains sub keys:
[2017-01-26 15:25:29Z INFO NetFrameworkUtil]  'Setup'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0\Setup', value name 'Version' is null.
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name 'Version' is null.
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name '' is null.
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4' contains sub keys:
[2017-01-26 15:25:29Z INFO NetFrameworkUtil]  'Client'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil]  'Full'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Version': '4.6.01586'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Install': '1'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Release': '394802'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Type is System.Int32
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Interpreted version: 4.6.2
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Version': '4.6.01586'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Install': '1'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Release': '394802'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Type is System.Int32
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Interpreted version: 4.6.2
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name 'Version' is null.
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name '': 'deprecated'
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Found 2 versions:
[2017-01-26 15:25:29Z INFO NetFrameworkUtil]  4.6.2
[2017-01-26 15:25:29Z INFO NetFrameworkUtil]  4.6.2
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Testing for min NET Framework version: '4.5'
[2017-01-26 15:25:29Z INFO CommandLineParser] Parse
[2017-01-26 15:25:29Z INFO CommandLineParser] Parsing 12 args
[2017-01-26 15:25:29Z INFO CommandLineParser] parsing argument
[2017-01-26 15:25:29Z INFO CommandLineParser] HasArgs: False
[2017-01-26 15:25:29Z INFO CommandLineParser] Adding Command: configure
[2017-01-26 15:25:29Z INFO CommandLineParser] parsing argument
[2017-01-26 15:25:29Z INFO CommandLineParser] HasArgs: True
[2017-01-26 15:25:29Z INFO CommandLineParser] arg: unattended
[2017-01-26 15:25:29Z INFO CommandLineParser] parsing argument
[2017-01-26 15:25:29Z INFO CommandLineParser] HasArgs: True
[2017-01-26 15:25:29Z INFO CommandLineParser] arg: url
[2017-01-26 15:25:29Z INFO CommandLineParser] Adding flag: unattended
[2017-01-26 15:25:29Z INFO CommandLineParser] parsing argument
[2017-01-26 15:25:29Z INFO CommandLineParser] HasArgs: True
[2017-01-26 15:25:29Z INFO CommandLineParser] Adding option 'url': 'https://alexlexproj.visualstudio.com'
[2017-01-26 15:25:29Z INFO CommandLineParser] parsing argument
[2017-01-26 15:25:29Z INFO CommandLineParser] HasArgs: True
[2017-01-26 15:25:29Z INFO CommandLineParser] arg: agent
[2017-01-26 15:25:29Z INFO CommandLineParser] parsing argument
[2017-01-26 15:25:29Z INFO CommandLineParser] HasArgs: True
[2017-01-26 15:25:29Z INFO CommandLineParser] Adding option 'agent': 'agent1'
[2017-01-26 15:25:29Z INFO CommandLineParser] parsing argument
[2017-01-26 15:25:29Z INFO CommandLineParser] HasArgs: True
[2017-01-26 15:25:29Z INFO CommandLineParser] arg: pool
[2017-01-26 15:25:29Z INFO CommandLineParser] parsing argument
[2017-01-26 15:25:29Z INFO CommandLineParser] HasArgs: True
[2017-01-26 15:25:29Z INFO CommandLineParser] Adding option 'pool': 'Default'
[2017-01-26 15:25:29Z INFO CommandLineParser] parsing argument
[2017-01-26 15:25:29Z INFO CommandLineParser] HasArgs: True
[2017-01-26 15:25:29Z INFO CommandLineParser] arg: auth
[2017-01-26 15:25:29Z INFO CommandLineParser] parsing argument
[2017-01-26 15:25:29Z INFO CommandLineParser] HasArgs: True
[2017-01-26 15:25:29Z INFO CommandLineParser] Adding option 'auth': 'PAT'
[2017-01-26 15:25:29Z INFO CommandLineParser] parsing argument
[2017-01-26 15:25:29Z INFO CommandLineParser] HasArgs: True
[2017-01-26 15:25:29Z INFO CommandLineParser] arg: token
[2017-01-26 15:25:29Z INFO CommandLineParser] parsing argument
[2017-01-26 15:25:29Z INFO CommandLineParser] HasArgs: True
[2017-01-26 15:25:29Z INFO CommandLineParser] Adding option 'token': '********'
[2017-01-26 15:25:29Z INFO AgentProcess] Arguments parsed
[2017-01-26 15:25:29Z INFO ProxyConfiguration] No proxy setting found.
[2017-01-26 15:25:29Z INFO Agent] ExecuteCommand
[2017-01-26 15:25:29Z INFO ConfigurationStore] currentAssemblyLocation: C:\build\agent\bin\Agent.Listener.dll
[2017-01-26 15:25:29Z INFO ConfigurationStore] binPath: C:\build\agent\bin
[2017-01-26 15:25:29Z INFO ConfigurationStore] RootFolder: C:\build\agent
[2017-01-26 15:25:29Z INFO ConfigurationStore] ConfigFilePath: C:\build\agent\.agent
[2017-01-26 15:25:29Z INFO ConfigurationStore] CredFilePath: C:\build\agent\.credentials
[2017-01-26 15:25:29Z INFO ConfigurationStore] ServiceConfigFilePath: C:\build\agent\.service
[2017-01-26 15:25:29Z INFO CommandSettings] Flag 'help': 'False'
[2017-01-26 15:25:29Z INFO CommandSettings] Flag 'version': 'False'
[2017-01-26 15:25:29Z INFO CommandSettings] Flag 'commit': 'False'
[2017-01-26 15:25:29Z INFO CommandSettings] Command 'configure': 'True'
[2017-01-26 15:25:29Z INFO ConfigurationManager] ConfigureAsync
[2017-01-26 15:25:29Z INFO ConfigurationStore] IsConfigured()
[2017-01-26 15:25:29Z INFO ConfigurationStore] IsConfigured: False
[2017-01-26 15:25:29Z INFO ConfigurationManager] Is configured: False
[2017-01-26 15:25:29Z INFO NetFrameworkUtil] Testing for min NET Framework version: '4.6'
[2017-01-26 15:25:29Z INFO CommandSettings] Flag 'machinegroup': 'False'
[2017-01-26 15:25:29Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2017-01-26 15:25:29Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2017-01-26 15:25:29Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.MachineGroupAgentConfigProvider, Agent.Listener
[2017-01-26 15:25:29Z INFO Terminal] WRITE LINE: 
[2017-01-26 15:25:29Z INFO Terminal] WRITE LINE: >> Connect:
[2017-01-26 15:25:29Z INFO Terminal] WRITE LINE: 
[2017-01-26 15:25:29Z INFO CommandSettings] Arg 'url': 'https://alexlexproj.visualstudio.com'
[2017-01-26 15:25:29Z INFO CommandSettings] Remove url from Arg dictionary.
[2017-01-26 15:25:29Z INFO ConfigurationManager] GetCredentialProvider
[2017-01-26 15:25:29Z INFO CommandSettings] Arg 'auth': 'PAT'
[2017-01-26 15:25:29Z INFO CommandSettings] Remove auth from Arg dictionary.
[2017-01-26 15:25:29Z INFO ConfigurationManager] Creating credential for auth: PAT
[2017-01-26 15:25:29Z INFO CredentialManager] GetCredentialProvider
[2017-01-26 15:25:29Z INFO CredentialManager] Creating type PAT
[2017-01-26 15:25:29Z INFO CredentialManager] Creating credential type: PAT
[2017-01-26 15:25:29Z INFO PersonalAccessToken] EnsureCredential
[2017-01-26 15:25:29Z INFO CommandSettings] Arg 'token': '********'
[2017-01-26 15:25:29Z INFO CommandSettings] Remove token from Arg dictionary.
[2017-01-26 15:25:29Z INFO PersonalAccessToken] GetVssCredentials
[2017-01-26 15:25:29Z INFO PersonalAccessToken] token retrieved: 50 chars
[2017-01-26 15:25:29Z INFO ConfigurationManager] cred retrieved
[2017-01-26 15:25:29Z INFO Terminal] WRITE LINE: Connecting to server ...
[2017-01-26 15:25:30Z INFO CommandSettings] Flag 'unattended': 'True'
[2017-01-26 15:25:30Z ERR  Agent] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The parameter is incorrect
   at System.Net.Http.WinHttpAuthHelper.SetWinHttpCredential(SafeWinHttpHandle requestHandle, ICredentials credentials, Uri uri, UInt32 authScheme, UInt32 authTarget)
   at System.Net.Http.WinHttpAuthHelper.CheckResponseForAuthentication(WinHttpRequestState state, UInt32& proxyAuthScheme, UInt32& serverAuthScheme)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider.<TestConnectionAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<ExecuteCommand>d__9.MoveNext()
[2017-01-26 15:25:30Z ERR  Terminal] WRITE ERROR: An error occurred while sending the request.

```
I will very appreciate any help because I ran out of ideas.

**Comment by TingluoHuang** [comment] 2017-01-26 15:48
@alparamonov can you check whether your PAT expired or doesn't have correct permission scope?

**Comment by alparamonov** [comment] 2017-01-26 15:51
@TingluoHuang thank you for your very fast reply. I've edited my initial post. 

> The same command works perfect from the host where the container runs.

The token is fine, I've recreated it a couple of times. Now it is authorized for all scopes.

**Comment by TingluoHuang** [comment] 2017-01-26 15:55
@alparamonov is there any http proxy between the container and the host?

**Comment by alparamonov** [comment] 2017-01-26 15:57
@TingluoHuang this is a simple virtual machine running on Azure. It was created from `Windows Server 2016 with Containers` template with default settings.

**Comment by TingluoHuang** [comment] 2017-01-26 16:09
@alparamonov can you try to capture Fiddler trace in your container? I guess for some reason, the auth header is not been send out.

**Comment by alparamonov** [comment] 2017-01-27 11:35
@TingluoHuang excuse me for the delayed answer. I could not manage to force Fiddler capture traffic from container. But I gathered similar data with WireShark running it directly on docker host and capturing packets from Container network adapter. The log file can be downloaded [here](https://alexshare.blob.core.windows.net/blobcont/vsts_agent_con.pcapng)

I hope it helps to clarify what's going wrong there.

**Comment by TingluoHuang** [comment] 2017-01-27 14:56
@alparamonov Can you RDP into the container VM? i need the decrypted https traffic. WireShark only give me the raw tcp traffic.

**Comment by ericsciple** [comment] 2017-01-27 15:01
@alparamonov you may need to [configure the agent to use the proxy url](https://www.visualstudio.com/en-us/docs/build/troubleshooting#http-trace-logs)

**Comment by alparamonov** [comment] 2017-01-28 19:18
@TingluoHuang @ericsciple thank you guys for your support! I made this running. Sadly, I don't exactly understand the issue I had.

I was playing around with Fiddler settings on a normal machine outside of container in order to make it capture outgoing traffic of the container. For that, I was testing an unattended configuration of an agent on the same machine. I've got the same error on that machine as in the container. When I configured https-traffic decryption in Fiddler, I found a 404 page as an answer from my `https://alexlexproj.visualstudio.com` team services. The behavior was reproducible. Then I added a trailing slash to the url `https://alexlexproj.visualstudio.com/` and it suddenly could connect but I've got another error during compatibility check. The same was now in the container. My agent pool at this point was empty (I refreshed the page several times), but nevertheless I executed a remove command. It didn't complain and removed a non-existing agent.

Now I can add and delete agents from within containers and also from ordinary machines. I am still confused what was it exactly, but at least it works now for me.

**Comment by TingluoHuang** [comment] 2017-01-28 20:48
@alparamonov that's weird, did you had a chance take a fiddler trace while this happen, can you still repro it?

**Comment by alparamonov** [comment] 2017-01-28 21:55
@TingluoHuang no... the connection mechanism works now like a charm. I automated the procedure of creating new containers with agents adding them to VSTS automatically, and since then it did not fail even once.

**Comment by TingluoHuang** [comment] 2017-01-29 02:25
@alparamonov even you didn't add trailing `/` to the end of your vsts url?

**Comment by alparamonov** [comment] 2017-01-29 12:20
@TingluoHuang yes, now it works both ways: with and without `/`

**Comment by TingluoHuang** [comment] 2017-02-01 18:35
@alparamonov I guess Fiddler might 'fix' your host machine. :) close the issue for now.

**Closed by TingluoHuang** 2017-02-01 18:35 UTC

**Comment by tekguy** [comment] 2017-03-03 19:48
I am also having this issue.  Here is my error, I tried with and without the "/" as recommended at the end of the URL (Fiddler is not installed). I will install it now and try. This happens on a Windows 2012 server:

17-03-03 19:44:47Z INFO Terminal] WRITE LINE: Connecting to the server.
[2017-03-03 19:44:47Z INFO CommandSettings] Flag 'unattended': 'False'
[2017-03-03 19:44:47Z ERR  Terminal] WRITE ERROR (exception):
[2017-03-03 19:44:47Z ERR  Terminal] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The parameter is incorrect
   at System.Net.Http.WinHttpAuthHelper.SetWinHttpCredential(SafeWinHttpHandle requestHandle, ICredentials credentials, Uri uri, UInt32 authScheme, UInt32 authTarget)
   at System.Net.Http.WinHttpAuthHelper.CheckResponseForAuthentication(WinHttpRequestState state, UInt32& proxyAuthScheme, UInt32& serverAuthScheme)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__7.MoveNext()
[2017-03-03 19:44:47Z ERR  Terminal] WRITE ERROR: Failed to add the agent.  Try again or ctrl-c to quit

**Comment by tekguy** [comment] 2017-03-03 19:59
Update: I installed fiddler, It seems I am making a post to https://codeism.visualstudio.com/_apis/distributedtask/pools/1/agents with a lot of personal data (roaming profile paths, etc). But I get a 401 unauthorized. I went ahead and created a new PAT and tried but same response.

HTTP/1.1 401 Unauthorized
Server: Microsoft-IIS/10.0
X-TFS-ProcessId: e2ffb1ec-7205-4b5e-af22-4d045dbb1348
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-FRAME-OPTIONS: SAMEORIGIN
WWW-Authenticate: Basic realm="https://tfsprodcus1.app.visualstudio.com/"
X-Powered-By: ASP.NET
X-Content-Type-Options: nosniff
Date: Fri, 03 Mar 2017 19:54:15 GMT
Content-Length: 0

**Comment by alparamonov** [comment] 2017-03-03 20:10
@tekguy looks like it happens on stage when the capabilities data is sent to TFS. Can you make sure, that you definitely don't have any rests of your previous agents in the build pool? Even if you don't see anything on TFS webpage, try to explicitly remove the agent you are trying to create first with `remove` option of `config` script. Then try to recreate it again. The bad thing, as I mentioned above, I could not figure out exactly what was causing the issue for me. But this is something I remember I did.

**Comment by tekguy** [comment] 2017-03-03 20:21
@alparamonov I've verified it doesn't exist on the site, I am not familiar with the remove option, do you have a link to documentation on this?

**Comment by alparamonov** [comment] 2017-03-03 20:28
@tekguy  [MS Documentation config.cmd](https://www.visualstudio.com/en-us/docs/build/actions/agents/v2-windows#remove-and-re-configure-an-agent)

Or simply try built-in help using `.\config.cmd --help`. They have some great examples there.
If you used PAT, this is the option of your choice:
`.\config.cmd remove --unattended --auth PAT --token <token>`

**Comment by TingluoHuang** [comment] 2017-03-03 21:15
@tekguy is your PAT has correct auth Scope? should have Pool Manage scope.

**Comment by tekguy** [comment] 2017-03-03 21:31
@TingluoHuang @alparamonov I got it to work! @TingluoHuang  I verified I have the right scopes selected Agent Pools (read) and Agent Pools (read, manage). 

So simply what I did was delete the folder I placed the agent and then ran it in unattended mode the first time and all seems well. I am still not sure what was wrong though.

**Comment by alparamonov** [comment] 2017-03-03 21:35
Did you try removing the agent? Or you have just deleted the folder?

**Comment by ericsciple** [comment] 2017-03-03 21:39
@tekguy are you pool administrator? also make sure you followed the prereqs (linked from readme.md in root of this repo)

**Comment by tekguy** [comment] 2017-03-03 21:42
@alparamonov I just deleted the folder. I also have fiddler running now maybe that has something to do with it? Over the weekend I will restart the machine and try again to see if I can nail down the cause.

**Comment by ericsciple** [comment] 2017-03-03 21:44
nevermind my question. i missed part of the thread

**Comment by judavi** [comment] 2017-07-26 15:13
I don't know if this could be useful for someone but I had a similar issue at the moment of running the agent, I solved it adding the certificates of our TFS server.

**Comment by biiiipy** [comment] 2019-02-20 10:54
@judavi thank you so much! That solved my issue! I trusted our root cert, but had to also add intermediate certificate.
