### ISSUE TITLE
Nuget Version Needs updating to latest

### ISSUE THREAD

**Issue by JKennedy24** [Microsoft/vsts-agent#657] opened 2016-10-25 09:32 UTC
## **Agent version and platform**
2.107.0
<br>
Windows 10
<br>
## **VSTS type and version**
VisualStudio.com
<br>
http://GmpSoftware.visualstudio.com
<br>
## **What's not working?** 
Nuget cannot install Microsoft.NETCore.UniversalWindowsPlatform V5.2.2 on my UWP project
It used to work with V5.0.0 but now get an error 
2016-10-24T22:02:16.4598735Z ##[error]Error: C:\agent\_work\_tasks\NuGetInstaller_333b11bd-d341-40d9-afcf-b32d5ce6f23b\0.2.22\node_modules\nuget-task-common\NuGet\3.3.0\NuGet.exe failed with return code: 1
2016-10-24T22:02:16.4598735Z ##[error]Packages failed to install

On my machine using Visual Studio Nuget 3.5.0 it works fine
<br>
## **Agent and Worker's diag log**
[logs_589.zip](https://github.com/Microsoft/vsts-agent/files/550175/logs_589.zip)

**Comment by bryanmacfarlane** [comment] 2016-10-25 10:59
Dupe of https://github.com/Microsoft/vsts-agent/issues/582 

Read discussion there.  I will send this to packaging team as well.

**Closed by bryanmacfarlane** 2016-10-25 10:59 UTC
Labels: duplicate
