### ISSUE TITLE
Agent fails to download artifacts from a renamed artifact source

### ISSUE THREAD

**Issue by agc93** [Microsoft/vsts-agent#741] opened 2017-01-03 04:19 UTC
## **Agent version and platform**
Version of your agent? 1.95.3  
OS of the machine running the agent? Windows Server 2012 R2  

## **VSTS type and version**
On-Prem TFS 2015 Update 3

## **What's not working?** 

After renaming a linked build definition, the "Download artifacts" task attempts to download the linked artifact using the old definition name. As a result, subsequent tasks fail since the artifact (downloaded into `$(System.DefaultWorkingDirectory)`) has the old definition name.

The logs for the Download artifacts step shows the message: 

```
Downloading linked artifact: OLD_NAME_HERE
Created artifact folder e:\b\Agent3\_work\df223b81b\OLD_NAME_HERE
...
Downloaded linked artifact OLD_NAME_HERE
```

Further the `BUILD_DEFINITIONNAME` environment variable still shows the old value.

> The updated definition name is shown in the *Artifacts* tab

Unlinking and relinking the renamed build definition resolves the issue.

**Comment by ericsciple** [comment] 2017-01-03 15:34
@GitHubSriramB is this an agent issue or a server side issue? is this by design?

**Comment by GitHubSriramB** [comment] 2017-01-04 00:24
This appears to be a server-side issue. Will check if it repros with 2.x agent also & get back.

**Comment by GitHubSriramB** [comment] 2017-01-11 09:54
@agc93 - I initially thought renaming build definition is causing download to fail. But after reading the description, I realize that the failure here is in a subsequent task once download completed.

We download the artifact to a folder that is named with the alias of the artifact source within the Release Definition. The alias does not change upon renaming the artifact. It is in fact a way to guard against such scenarios. Deployment scripts would use the invariant alias to resolve paths and so will not get impacted when the build definition gets renamed.


We store/cache the build definition name within a Release Definition and we don't update it automatically when the build definition gets renamed. Only when the artifact source gets edited, we will fetch the new build definition name & prompt to save the artifact source explicitly. This change also gets audited in the release definition history. Since we don't updat the build definition name automatically within release definition, BUILD_DEFINITIONNAME also doesn't get updated automatically. This is our current behavior. 

Is the task that is failing using the build definition name to resolve path? If so, pl. change it to refer to the alias instead. This way the task will continue to work until the alias remains the same (irrespective of build definition getting renamed).

**Comment by bryanmacfarlane** [comment] 2017-06-03 17:13
@agc93 @GitHubSriramB - It's unclear what's left to be done with this issue

**Comment by GitHubSriramB** [comment] 2017-06-04 23:26
@agc93 - Pl. refer to comment above on how to resolve this issue. If you have any further queries, pl. let us know. I am closing this as of now.

**Closed by GitHubSriramB** 2017-06-04 23:26 UTC
