### ISSUE TITLE
"not equal" agents demands in yaml build definition 

### ISSUE THREAD

**Issue by melezhik** [Microsoft/vsts-agent#1740] opened 2018-08-01 13:53 UTC
Hi vsts devs! I have found in documentation and wonder if it possible to have a "not equal" agent demands in yaml build definitions?

```

resources:

- repo: self

queue:
  name: Q1
  demands:
   - Param1 -nequals Value1

```

Best

Alexey

**Comment by TingluoHuang** [comment] 2018-08-01 16:12
@melezhik we don't have a `not equals` demand operator. we only have `exists` or `equals`

```
queue:
  demands:
  - msbuild //exists demand
  - msbuildversion -equals 15.0 // equals demand
```
I am going to close this issue as by designed for now.

**Closed by TingluoHuang** 2018-08-01 16:12 UTC
Labels: Area: YAML

**Comment by melezhik** [comment] 2018-08-01 16:31
Thanks @tanvi-soni . Can I make a feature request?

**Comment by tarzanboy13** [comment] 2025-03-14 15:52
Why you don't have this feature ? This is unacceptable.
