### ISSUE TITLE
Agent failing to connect to the vso online on configure

### ISSUE THREAD

**Issue by rusty21** [Microsoft/vsts-agent#327] opened 2016-06-23 16:57 UTC
I'm upgrading from the old agent to this new agent. I downloaded vsts-agent-osx.10.11-x64-2.102.0.tar.gz for Mac osx. Went to configure it, accepted the license agreement.  I entered in the server url in the form https://myvsoolineaccount.visualstudio.com entered in my PAT and I get this error:
Connecting to server ...
The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
Failed to connect.  Try again or ctrl-c to quit

This exact same address worked on the old agent I was using. Am I doing something wrong?

**Comment by bryanmacfarlane** [comment] 2016-06-23 22:40
This is a dupe

See docs about system requirements.  Your OpenSSL is not right

**Comment by bryanmacfarlane** [comment] 2016-06-23 22:42
Dupe of #110 and #232

**Closed by bryanmacfarlane** 2016-06-23 22:42 UTC
