### ISSUE TITLE
Unable to connect to server using private build agent for OS X High Sierra

### ISSUE THREAD

**Issue by awentzel** [Microsoft/vsts-agent#1310] opened 2017-11-29 03:29 UTC
## Agent version and platform
Version of your agent?  2.124.0 / OS X 10.11-x64 which seems to be the only one available.

## OS of the machine running the agent? 
OS X 10.13.1 (17B48) 

## VSTS type and version
Visual Studio.com
fluentweb.visualstudio.com - MS Internal Account

## What's not working?
Also, posted on SO: https://stackoverflow.microsoft.com/questions/75328/unable-to-connect-to-server-while-created-a-private-build-agent

> Enter server URL > https://fluentweb.visualstudio.com
Enter authentication type (press enter for PAT) > PAT
Enter personal access token > ****************************************************
Connecting to server ...
The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
Failed to connect.  Try again or ctrl-c to quit

## Agent and Worker's diag log
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here. 

> [2017-11-29 02:52:03Z INFO CommandSettings] Arg 'url': ''
[2017-11-29 02:52:03Z INFO CommandSettings] Flag 'unattended': 'False'
[2017-11-29 02:52:03Z INFO PromptManager] ReadValue
[2017-11-29 02:52:03Z INFO Terminal] WRITE: Enter server URL >
[2017-11-29 02:52:03Z INFO Terminal] READ LINE
[2017-11-29 02:56:53Z INFO Terminal] Read value: 'https://fluentweb.visualstudio.com'
[2017-11-29 02:56:53Z INFO ConfigurationManager] GetCredentialProvider
[2017-11-29 02:56:53Z INFO CommandSettings] Arg 'auth': ''
[2017-11-29 02:56:53Z INFO CommandSettings] Flag 'unattended': 'False'
[2017-11-29 02:56:53Z INFO PromptManager] ReadValue
[2017-11-29 02:56:53Z INFO Terminal] WRITE: Enter authentication type (press enter for PAT) >
[2017-11-29 02:56:53Z INFO Terminal] READ LINE
[2017-11-29 02:56:56Z INFO Terminal] Read value: 'PAT'
[2017-11-29 02:56:56Z INFO ConfigurationManager] Creating credential for auth: PAT
[2017-11-29 02:56:56Z INFO CredentialManager] GetCredentialProvider
[2017-11-29 02:56:56Z INFO CredentialManager] Creating type PAT
[2017-11-29 02:56:56Z INFO CredentialManager] Creating credential type: PAT
[2017-11-29 02:56:56Z INFO PersonalAccessToken] EnsureCredential
[2017-11-29 02:56:56Z INFO CommandSettings] Arg 'token': ''
[2017-11-29 02:56:56Z INFO CommandSettings] Flag 'unattended': 'False'
[2017-11-29 02:56:56Z INFO PromptManager] ReadValue
[2017-11-29 02:56:56Z INFO Terminal] WRITE: Enter personal access token >
[2017-11-29 02:56:56Z INFO Terminal] READ SECRET
[2017-11-29 02:57:31Z INFO Terminal] Read value: '********'
[2017-11-29 02:57:31Z INFO PersonalAccessToken] GetVssCredentials
[2017-11-29 02:57:31Z INFO PersonalAccessToken] token retrieved: 52 chars
[2017-11-29 02:57:31Z INFO ConfigurationManager] cred retrieved
[2017-11-29 02:57:31Z INFO Terminal] WRITE LINE: Connecting to server ...
[2017-11-29 02:57:31Z INFO CommandSettings] Flag 'unattended': 'False'
[2017-11-29 02:57:31Z ERR  Terminal] WRITE ERROR (exception):
[2017-11-29 02:57:31Z ERR  Terminal] System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.CryptoInitializer.Initialize()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.HttpInitializer.Initialize()
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at Microsoft.VisualStudio.Services.Agent.Util.ApiUtil.CreateConnection(Uri serverUri, VssCredentials credentials, IEnumerable`1 additionalDelegatingHandler)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider.<TestConnectionAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__6.MoveNext()
[2017-11-29 02:57:31Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit

I attempted to resolve this issue by following prerequisites from https://github.com/Microsoft/vsts-agent/blob/master/docs/start/envosx.md 

> ./config.sh: line 29: 14212 Segmentation fault: 11  ./bin/Agent.Listener configure "$@"

I then attempted to resolve this issue with exact instructions from ticket @470 as posted in the last comment.  But got a similar error.

> ./config.sh: line 29: 14261 Segmentation fault: 11  ./bin/Agent.Listener configure "$@"

**Comment by bryanmacfarlane** [comment] 2017-11-29 03:37
Duplicate of https://github.com/Microsoft/vsts-agent/issues/1007

**Closed** 2017-11-29 03:37 UTC
