### ISSUE TITLE
Custom conditions cannot be edited inside task groups

### ISSUE THREAD

**Issue by sibbl** [Microsoft/vsts-agent#1290] opened 2017-11-09 10:35 UTC
We're heavily using custom conditions and task groups. However, the task groups editor does not support editing custom conditions of tasks - seems like it was not part of #711 .

Reproduce steps:
1. Create 2 tasks in a build definition
2. Add "false" as the custom condition to the 2nd task
3. Combine these 2 tasks into a task group
4. Try to change the custom condition of the 2nd "false" to "true".

I didn't find a way to manage this yet. My workaround currently is to export the task group, modify the JSON manually and import it again. However, I need to go into every phase which referenced the old task group and need to add it again, adding all parameters again... Is there an easier way or will this functionality be added in the future?

**Comment by MireilleHanna** [comment] 2017-11-14 15:03
it is on our backlog

**Comment by bryanmacfarlane** [comment] 2017-11-16 03:42
Yeah, the issue is the task group editor isn't using the new editor which supports conditions.  Being worked on.  Closing since it's not an agent issue.

**Closed by bryanmacfarlane** 2017-11-16 03:42 UTC
